// Irregular verb table for the conjugation engine.
// Keys are base infinitives (or pseudo-bases such as "durre", "cludere" used only through prefixes).
// Fields (all optional):
//   cls      conjugation class override: 'are' | 'ere' | 'ire'
//   stem     secondary stem used for regular endings (imperfetto, congiuntivo imperfetto, gerundio, regular passato remoto persons, present when not overridden)
//   pres     6 present-indicative forms
//   imperf   6 imperfetto forms
//   pr       passato remoto: a strong stem (used for io / lui / loro: -i, -e, -ero) or 6 full forms
//   fut      future / conditional stem (without endings)
//   subj     6 congiuntivo presente forms
//   subjImp  6 congiuntivo imperfetto forms
//   imp      5 imperative forms (tu, Lei, noi, voi, Loro); null = no imperative
//   pp       participio passato
//   ger      gerundio
//   isc      -isc- present (only for -ire)
// Alternatives inside a form are separated with "|" (first is primary).

export const IRREGULAR = {
  essere: { pres: ['sono', 'sei', 'è', 'siamo', 'siete', 'sono'], imperf: ['ero', 'eri', 'era', 'eravamo', 'eravate', 'erano'], pr: ['fui', 'fosti', 'fu', 'fummo', 'foste', 'furono'], fut: 'sar', subj: ['sia', 'sia', 'sia', 'siamo', 'siate', 'siano'], subjImp: ['fossi', 'fossi', 'fosse', 'fossimo', 'foste', 'fossero'], imp: ['sii', 'sia', 'siamo', 'siate', 'siano'], pp: 'stato', ger: 'essendo' },
  avere: { pres: ['ho', 'hai', 'ha', 'abbiamo', 'avete', 'hanno'], pr: 'ebb', fut: 'avr', subj: ['abbia', 'abbia', 'abbia', 'abbiamo', 'abbiate', 'abbiano'], imp: ['abbi', 'abbia', 'abbiamo', 'abbiate', 'abbiano'], pp: 'avuto' },
  andare: { pres: ['vado', 'vai', 'va', 'andiamo', 'andate', 'vanno'], fut: 'andr', imp: ["va'|vai", 'vada', 'andiamo', 'andate', 'vadano'] },
  stare: { pres: ['sto', 'stai', 'sta', 'stiamo', 'state', 'stanno'], pr: ['stetti', 'stesti', 'stette', 'stemmo', 'steste', 'stettero'], fut: 'star', subj: ['stia', 'stia', 'stia', 'stiamo', 'stiate', 'stiano'], subjImp: ['stessi', 'stessi', 'stesse', 'stessimo', 'steste', 'stessero'], imp: ["sta'|stai", 'stia', 'stiamo', 'state', 'stiano'], pp: 'stato' },
  dare: { pres: ['do', 'dai', 'dà', 'diamo', 'date', 'danno'], pr: ['diedi|detti', 'desti', 'diede|dette', 'demmo', 'deste', 'diedero|dettero'], fut: 'dar', subj: ['dia', 'dia', 'dia', 'diamo', 'diate', 'diano'], subjImp: ['dessi', 'dessi', 'desse', 'dessimo', 'deste', 'dessero'], imp: ["da'|dai", 'dia', 'diamo', 'date', 'diano'], pp: 'dato' },
  fare: { cls: 'ere', stem: 'fac', pres: ['faccio', 'fai', 'fa', 'facciamo', 'fate', 'fanno'], pr: 'fec', fut: 'far', subj: ['faccia', 'faccia', 'faccia', 'facciamo', 'facciate', 'facciano'], imp: ["fa'|fai", 'faccia', 'facciamo', 'fate', 'facciano'], pp: 'fatto' },
  dire: { cls: 'ere', stem: 'dic', pres: ['dico', 'dici', 'dice', 'diciamo', 'dite', 'dicono'], pr: 'diss', fut: 'dir', imp: ["di'", 'dica', 'diciamo', 'dite', 'dicano'], pp: 'detto' },
  bere: { cls: 'ere', stem: 'bev', pr: 'bevv', fut: 'berr', pp: 'bevuto' },
  porre: { cls: 'ere', stem: 'pon', pres: ['pongo', 'poni', 'pone', 'poniamo', 'ponete', 'pongono'], pr: 'pos', fut: 'porr', pp: 'posto' },
  trarre: { cls: 'ere', stem: 'tra', pres: ['traggo', 'trai', 'trae', 'traiamo', 'traete', 'traggono'], pr: 'trass', fut: 'trarr', pp: 'tratto' },
  durre: { cls: 'ere', stem: 'duc', pr: 'duss', fut: 'durr', pp: 'dotto' },
  venire: { pres: ['vengo', 'vieni', 'viene', 'veniamo', 'venite', 'vengono'], pr: 'venn', fut: 'verr', pp: 'venuto', isc: false },
  tenere: { pres: ['tengo', 'tieni', 'tiene', 'teniamo', 'tenete', 'tengono'], pr: 'tenn', fut: 'terr' },
  volere: { pres: ['voglio', 'vuoi', 'vuole', 'vogliamo', 'volete', 'vogliono'], pr: 'voll', fut: 'vorr', imp: ['vogli', 'voglia', 'vogliamo', 'vogliate', 'vogliano'] },
  potere: { pres: ['posso', 'puoi', 'può', 'possiamo', 'potete', 'possono'], fut: 'potr', imp: null },
  dovere: { pres: ['devo|debbo', 'devi', 'deve', 'dobbiamo', 'dovete', 'devono|debbono'], fut: 'dovr', subj: ['debba', 'debba', 'debba', 'dobbiamo', 'dobbiate', 'debbano'], imp: null },
  sapere: { pres: ['so', 'sai', 'sa', 'sappiamo', 'sapete', 'sanno'], pr: 'sepp', fut: 'sapr', subj: ['sappia', 'sappia', 'sappia', 'sappiamo', 'sappiate', 'sappiano'], imp: ['sappi', 'sappia', 'sappiamo', 'sappiate', 'sappiano'] },
  uscire: { pres: ['esco', 'esci', 'esce', 'usciamo', 'uscite', 'escono'], isc: false },
  salire: { pres: ['salgo', 'sali', 'sale', 'saliamo', 'salite', 'salgono'], isc: false },
  morire: { pres: ['muoio', 'muori', 'muore', 'moriamo', 'morite', 'muoiono'], fut: 'morir|morr', pp: 'morto', isc: false },
  udire: { pres: ['odo', 'odi', 'ode', 'udiamo', 'udite', 'odono'], fut: 'udir|udr', isc: false },
  cucire: { pres: ['cucio', 'cuci', 'cuce', 'cuciamo', 'cucite', 'cuciono'], isc: false },
  rimanere: { pres: ['rimango', 'rimani', 'rimane', 'rimaniamo', 'rimanete', 'rimangono'], pr: 'rimas', fut: 'rimarr', pp: 'rimasto' },
  valere: { pres: ['valgo', 'vali', 'vale', 'valiamo', 'valete', 'valgono'], pr: 'vals', fut: 'varr', pp: 'valso' },
  dolere: { pres: ['dolgo', 'duoli', 'duole', 'doliamo|dogliamo', 'dolete', 'dolgono'], pr: 'dols', fut: 'dorr', pp: 'doluto' },
  parere: { pres: ['paio', 'pari', 'pare', 'paiamo', 'parete', 'paiono'], pr: 'parv', fut: 'parr', pp: 'parso', imp: null },
  solere: { pres: ['soglio', 'suoli', 'suole', 'sogliamo', 'solete', 'sogliono'], pp: 'solito', imp: null },
  piacere: { pres: ['piaccio', 'piaci', 'piace', 'piacciamo', 'piacete', 'piacciono'], pr: 'piacqu', pp: 'piaciuto' },
  tacere: { pres: ['taccio', 'taci', 'tace', 'tacciamo', 'tacete', 'tacciono'], pr: 'tacqu', pp: 'taciuto' },
  giacere: { pres: ['giaccio', 'giaci', 'giace', 'giacciamo', 'giacete', 'giacciono'], pr: 'giacqu', pp: 'giaciuto' },
  nuocere: { pres: ['nuoccio|noccio', 'nuoci', 'nuoce', 'nociamo|nuociamo', 'nuocete|nocete', 'nuocciono|nocciono'], pr: 'nocqu', pp: 'nociuto' },
  cuocere: { pres: ['cuocio', 'cuoci', 'cuoce', 'cuociamo|cociamo', 'cuocete|cocete', 'cuociono'], pr: 'coss', pp: 'cotto' },
  nascere: { pr: 'nacqu', pp: 'nato' },
  conoscere: { pr: 'conobb', pp: 'conosciuto' },
  crescere: { pr: 'crebb', pp: 'cresciuto' },
  vivere: { pr: 'viss', pp: 'vissuto', fut: 'vivr' },
  cadere: { pr: 'cadd', fut: 'cadr' },
  godere: { fut: 'godr' },
  vedere: { pr: 'vid', pp: 'visto|veduto', fut: 'vedr' },
  provvedere: { pr: 'provvid', pp: 'provvisto|provveduto' },
  sedere: { pres: ['siedo|seggo', 'siedi', 'siede', 'sediamo', 'sedete', 'siedono|seggono'], subj: ['sieda|segga', 'sieda|segga', 'sieda|segga', 'sediamo', 'sediate', 'siedano|seggano'] },
  scegliere: { pres: ['scelgo', 'scegli', 'sceglie', 'scegliamo', 'scegliete', 'scelgono'], pr: 'scels', pp: 'scelto' },
  cogliere: { pres: ['colgo', 'cogli', 'coglie', 'cogliamo', 'cogliete', 'colgono'], pr: 'cols', pp: 'colto' },
  togliere: { pres: ['tolgo', 'togli', 'toglie', 'togliamo', 'togliete', 'tolgono'], pr: 'tols', pp: 'tolto' },
  sciogliere: { pres: ['sciolgo', 'sciogli', 'scioglie', 'sciogliamo', 'sciogliete', 'sciolgono'], pr: 'sciols', pp: 'sciolto' },
  spegnere: { pres: ['spengo', 'spegni', 'spegne', 'spegniamo', 'spegnete', 'spengono'], pr: 'spens', pp: 'spento' },
  // -ere verbs irregular only in passato remoto / participio
  chiudere: { pr: 'chius', pp: 'chiuso' },
  cludere: { pr: 'clus', pp: 'cluso' },
  ludere: { pr: 'lus', pp: 'luso' },
  prendere: { pr: 'pres', pp: 'preso' },
  mettere: { pr: 'mis', pp: 'messo' },
  scrivere: { pr: 'scriss', pp: 'scritto' },
  leggere: { pr: 'less', pp: 'letto' },
  rispondere: { pr: 'rispos', pp: 'risposto' },
  nascondere: { pr: 'nascos', pp: 'nascosto' },
  perdere: { pr: 'pers', pp: 'perso|perduto' },
  decidere: { pr: 'decis', pp: 'deciso' },
  cidere: { pr: 'cis', pp: 'ciso' },
  uccidere: { pr: 'uccis', pp: 'ucciso' },
  lidere: { pr: 'lis', pp: 'liso' },
  ridere: { pr: 'ris', pp: 'riso' },
  dividere: { pr: 'divis', pp: 'diviso' },
  vadere: { pr: 'vas', pp: 'vaso' },
  suadere: { pr: 'suas', pp: 'suaso' },
  radere: { pr: 'ras', pp: 'raso' },
  ledere: { pr: 'les', pp: 'leso' },
  rodere: { pr: 'ros', pp: 'roso' },
  mordere: { pr: 'mors', pp: 'morso' },
  ardere: { pr: 'ars', pp: 'arso' },
  plodere: { pr: 'plos', pp: 'ploso' },
  correre: { pr: 'cors', pp: 'corso' },
  vincere: { pr: 'vins', pp: 'vinto' },
  piangere: { pr: 'pians', pp: 'pianto' },
  spingere: { pr: 'spins', pp: 'spinto' },
  giungere: { pr: 'giuns', pp: 'giunto' },
  dipingere: { pr: 'dipins', pp: 'dipinto' },
  stringere: { pr: 'strins', pp: 'stretto' },
  fingere: { pr: 'fins', pp: 'finto' },
  tingere: { pr: 'tins', pp: 'tinto' },
  cingere: { pr: 'cins', pp: 'cinto' },
  pungere: { pr: 'puns', pp: 'punto' },
  ungere: { pr: 'uns', pp: 'unto' },
  mungere: { pr: 'muns', pp: 'munto' },
  frangere: { pr: 'frans', pp: 'franto' },
  piovere: { pr: 'piovv' },
  rompere: { pr: 'rupp', pp: 'rotto' },
  muovere: { pr: 'moss', pp: 'mosso' },
  scuotere: { pr: 'scoss', pp: 'scosso' },
  percuotere: { pr: 'percoss', pp: 'percosso' },
  chiedere: { pr: 'chies', pp: 'chiesto' },
  fondere: { pr: 'fus', pp: 'fuso' },
  scendere: { pr: 'sces', pp: 'sceso' },
  accendere: { pr: 'acces', pp: 'acceso' },
  difendere: { pr: 'difes', pp: 'difeso' },
  offendere: { pr: 'offes', pp: 'offeso' },
  spendere: { pr: 'spes', pp: 'speso' },
  appendere: { pr: 'appes', pp: 'appeso' },
  dipendere: { pr: 'dipes', pp: 'dipeso' },
  sospendere: { pr: 'sospes', pp: 'sospeso' },
  propendere: { pr: 'propes', pp: 'propeso' },
  tendere: { pr: 'tes', pp: 'teso' },
  rendere: { pr: 'res', pp: 'reso' },
  spandere: { pr: 'spans|spandett', pp: 'spanto|spanduto' },
  discutere: { pr: 'discuss', pp: 'discusso' },
  incutere: { pr: 'incuss', pp: 'incusso' },
  concedere: { pr: 'concess|concedett', pp: 'concesso' },
  succedere: { pr: 'success', pp: 'successo' },
  assumere: { pr: 'assuns', pp: 'assunto' },
  sumere: { pr: 'suns', pp: 'sunto' },
  primere: { pr: 'press', pp: 'presso' },
  redimere: { pr: 'redens', pp: 'redento' },
  nettere: { pr: 'ness', pp: 'nesso' },
  flettere: { pr: 'fless', pp: 'flesso' },
  riflettere: { pp: 'riflettuto|riflesso' },
  espellere: { pr: 'espuls', pp: 'espulso' },
  pellere: { pr: 'puls', pp: 'pulso' },
  eccellere: { pr: 'eccels', pp: 'eccelso' },
  solvere: { pr: 'sols', pp: 'solto' },
  evolvere: { pp: 'evoluto' },
  devolvere: { pp: 'devoluto' },
  volgere: { pr: 'vols', pp: 'volto' },
  porgere: { pr: 'pors', pp: 'porto' },
  scorgere: { pr: 'scors', pp: 'scorto' },
  accorgere: { pr: 'accors', pp: 'accorto' },
  sorgere: { pr: 'sors', pp: 'sorto' },
  spargere: { pr: 'spars', pp: 'sparso' },
  mergere: { pr: 'mers', pp: 'merso' },
  ergere: { pr: 'ers', pp: 'erto' },
  tergere: { pr: 'ters', pp: 'terso' },
  torcere: { pr: 'tors', pp: 'torto' },
  reggere: { pr: 'ress', pp: 'retto' },
  proteggere: { pr: 'protess', pp: 'protetto' },
  dirigere: { pr: 'diress', pp: 'diretto' },
  erigere: { pr: 'eress', pp: 'eretto' },
  esigere: { pp: 'esatto|esigito' },
  redigere: { pr: 'redass', pp: 'redatto' },
  prediligere: { pr: 'prediless', pp: 'prediletto' },
  negligere: { pr: 'negless', pp: 'negletto' },
  friggere: { pr: 'friss', pp: 'fritto' },
  affiggere: { pr: 'affiss', pp: 'affisso' },
  prefiggere: { pr: 'prefiss', pp: 'prefisso' },
  trafiggere: { pr: 'trafiss', pp: 'trafitto' },
  crocifiggere: { pr: 'crocifiss', pp: 'crocifisso' },
  sconfiggere: { pr: 'sconfiss', pp: 'sconfitto' },
  affliggere: { pr: 'affliss', pp: 'afflitto' },
  infliggere: { pr: 'infliss', pp: 'inflitto' },
  distruggere: { pr: 'distruss', pp: 'distrutto' },
  struggere: { pr: 'struss', pp: 'strutto' },
  distinguere: { pr: 'distins', pp: 'distinto' },
  estinguere: { pr: 'estins', pp: 'estinto' },
  rifulgere: { pr: 'rifuls', pp: 'rifulso' },
  fulgere: { pr: 'fuls', pp: 'fulso' },
  eleggere: { pr: 'eless', pp: 'eletto' },
  esplodere: { pr: 'esplos', pp: 'esploso' },
  emergere: { pr: 'emers', pp: 'emerso' },
  fendere: { pr: 'fend|fendett', pp: 'fesso|fenduto' },
  fungere: { pr: 'funs', pp: 'funto' },
  scindere: { pr: 'sciss', pp: 'scisso' },
  assurgere: { pr: 'assurs', pp: 'assurto' },
  transigere: { pp: 'transatto' },
  incidere: { pr: 'incis', pp: 'inciso' },
  coincidere: { pr: 'coincis', pp: 'coinciso' },
  recidere: { pr: 'recis', pp: 'reciso' },
  // -ire irregulars
  aprire: { pp: 'aperto', isc: false },
  coprire: { pp: 'coperto', isc: false },
  offrire: { pp: 'offerto', isc: false },
  soffrire: { pp: 'sofferto', isc: false },
  apparire: { pres: ['appaio', 'appari', 'appare', 'appariamo', 'apparite', 'appaiono'], pr: 'apparv', pp: 'apparso', isc: false },
  comparire: { pres: ['compaio', 'compari', 'compare', 'compariamo', 'comparite', 'compaiono'], pr: 'comparv', pp: 'comparso', isc: false },
  scomparire: { pres: ['scompaio', 'scompari', 'scompare', 'scompariamo', 'scomparite', 'scompaiono'], pr: 'scomparv', pp: 'scomparso', isc: false },
  trasparire: { pres: ['traspaio|trasparisco', 'traspari|trasparisci', 'traspare|trasparisce', 'traspariamo', 'trasparite', 'traspaiono|traspariscono'], pp: 'trasparso|trasparito', isc: false },
  seppellire: { pp: 'sepolto|seppellito', isc: true },
  compiere: { cls: 'ire', stem: 'compi', pp: 'compiuto', ger: 'compiendo', isc: false },
  adempiere: { cls: 'ire', stem: 'adempi', pp: 'adempiuto', ger: 'adempiendo', isc: false },
  empiere: { cls: 'ire', stem: 'empi', pp: 'empiuto', ger: 'empiendo', isc: false },
  riempire: { stem: 'riempi', ger: 'riempiendo', isc: false },
  empire: { stem: 'empi', ger: 'empiendo', isc: false },
};

// Verbs that must NOT be derived from a shorter base by prefix stripping (they are regular).
export const FORCE_REGULAR = new Set([
  'restare', 'prestare', 'imprestare', 'contrastare', 'sovrastare', 'costare', 'arrestare', 'sostare', 'distare', 'attestare', 'infestare',
  'circondare', 'mandare', 'ricordare', 'accordare', 'guardare', 'sondare', 'affondare', 'fondare', 'abbondare', 'inondare',
  'vendere', 'pendere', 'attendere', 'precedere', 'procedere', 'cedere', 'retrocedere', 'accedere', 'eccedere', 'incedere',
  'esistere', 'assistere', 'insistere', 'resistere', 'consistere', 'persistere', 'desistere', 'sussistere', 'coesistere',
  'battere', 'combattere', 'abbattere', 'dibattere', 'ribattere', 'temere', 'premere', 'spremere', 'gemere', 'fremere',
  'credere', 'ricevere', 'ripetere', 'vivacchiare', 'sparire', 'partire', 'ripartire', 'sentire', 'servire', 'seguire',
  'involvere',
  'pascere', 'mescere', 'ricredersi', 'sedersi', 'candire', 'sparare', 'stimare', 'stare', 'dare', 'fare', 'dire',
]);

// Derived verbs that cannot be resolved by generic prefix stripping.
export const DERIVED = {
  rifare: ['ri', 'fare'], disfare: ['dis', 'fare'], soddisfare: ['soddis', 'fare'], contraffare: ['contraf', 'fare'], sopraffare: ['sopraf', 'fare'],
  assuefare: ['assue', 'fare'], liquefare: ['lique', 'fare'], stupefare: ['stupe', 'fare'], rarefare: ['rare', 'fare'], strafare: ['stra', 'fare'], sfare: ['s', 'fare'],
  ridire: ['ri', 'dire'], contraddire: ['contrad', 'dire'], benedire: ['bene', 'dire'], maledire: ['male', 'dire'], predire: ['pre', 'dire'],
  disdire: ['dis', 'dire'], indire: ['in', 'dire'], interdire: ['inter', 'dire'], addire: ['ad', 'dire'],
  ridare: ['ri', 'dare'], ristare: ['ri', 'stare'], sottostare: ['sotto', 'stare'], soprastare: ['sopra', 'stare'],
  riuscire: ['ri', 'uscire'], fuoriuscire: ['fuori', 'uscire'], risapere: ['ri', 'sapere'], rivolere: ['ri', 'volere'], riavere: ['ri', 'avere'],
  riudire: ['ri', 'udire'], ricucire: ['ri', 'cucire'], scucire: ['s', 'cucire'],
  condurre: ['con', 'durre'], produrre: ['pro', 'durre'], ridurre: ['ri', 'durre'], tradurre: ['tra', 'durre'], introdurre: ['intro', 'durre'],
  dedurre: ['de', 'durre'], indurre: ['in', 'durre'], sedurre: ['se', 'durre'], riprodurre: ['ripro', 'durre'], addurre: ['ad', 'durre'],
  ricondurre: ['ricon', 'durre'], abdurre: ['ab', 'durre'], coprodurre: ['copro', 'durre'],
  concludere: ['con', 'cludere'], includere: ['in', 'cludere'], escludere: ['es', 'cludere'], precludere: ['pre', 'cludere'], occludere: ['oc', 'cludere'],
  alludere: ['al', 'ludere'], deludere: ['de', 'ludere'], illudere: ['il', 'ludere'], eludere: ['e', 'ludere'], colludere: ['col', 'ludere'], preludere: ['pre', 'ludere'],
  incidere: ['in', 'cidere'], coincidere: ['coin', 'cidere'], recidere: ['re', 'cidere'],
  elidere: ['e', 'lidere'], collidere: ['col', 'lidere'],
  evadere: ['e', 'vadere'], invadere: ['in', 'vadere'], pervadere: ['per', 'vadere'],
  persuadere: ['per', 'suadere'], dissuadere: ['dis', 'suadere'],
  implodere: ['im', 'plodere'],
  presumere: ['pre', 'sumere'], riassumere: ['rias', 'sumere'], desumere: ['de', 'sumere'],
  esprimere: ['es', 'primere'], comprimere: ['com', 'primere'], reprimere: ['re', 'primere'], opprimere: ['op', 'primere'],
  sopprimere: ['sop', 'primere'], imprimere: ['im', 'primere'], deprimere: ['de', 'primere'],
  connettere: ['con', 'nettere'], annettere: ['an', 'nettere'], sconnettere: ['scon', 'nettere'], disconnettere: ['discon', 'nettere'],
  repellere: ['re', 'pellere'], propellere: ['pro', 'pellere'], impellere: ['im', 'pellere'],
  risolvere: ['ri', 'solvere'], assolvere: ['as', 'solvere'], dissolvere: ['dis', 'solvere'],
  immergere: ['im', 'mergere'], sommergere: ['som', 'mergere'],
  detergere: ['de', 'tergere'],
  correggere: ['cor', 'reggere'], sorreggere: ['sor', 'reggere'],
  sorridere: ['sor', 'ridere'], deridere: ['de', 'ridere'], irridere: ['ir', 'ridere'],
  condividere: ['con', 'dividere'], suddividere: ['sud', 'dividere'],
  corrodere: ['cor', 'rodere'], erodere: ['e', 'rodere'],
  rimpiangere: ['rim', 'piangere'], compiangere: ['com', 'piangere'],
  aggiungere: ['ag', 'giungere'], raggiungere: ['rag', 'giungere'], congiungere: ['con', 'giungere'], disgiungere: ['dis', 'giungere'],
  soggiungere: ['sog', 'giungere'], sopraggiungere: ['soprag', 'giungere'], ingiungere: ['in', 'giungere'],
  respingere: ['re', 'spingere'], sospingere: ['so', 'spingere'],
  costringere: ['co', 'stringere'], restringere: ['re', 'stringere'], astringere: ['a', 'stringere'],
  attingere: ['at', 'tingere'], stingere: ['s', 'tingere'],
  recingere: ['re', 'cingere'], accingersi: ['ac', 'cingere'],
  espungere: ['es', 'pungere'],
  infrangere: ['in', 'frangere'],
  raccogliere: ['rac', 'cogliere'], accogliere: ['ac', 'cogliere'], ricogliere: ['ri', 'cogliere'],
  prescegliere: ['pre', 'scegliere'],
  distogliere: ['dis', 'togliere'],
  disciogliere: ['di', 'sciogliere'],
  rincorrere: ['rin', 'correre'], soccorrere: ['soc', 'correre'], occorrere: ['oc', 'correre'], accorrere: ['ac', 'correre'],
  scommettere: ['scom', 'mettere'], compromettere: ['compro', 'mettere'], frammettere: ['fram', 'mettere'], manomettere: ['mano', 'mettere'],
  intromettersi: ['intro', 'mettere'],
  appartenere: ['appar', 'tenere'], mantenere: ['man', 'tenere'], trattenere: ['trat', 'tenere'], intrattenere: ['intrat', 'tenere'],
  rattenere: ['rat', 'tenere'], astenersi: ['as', 'tenere'],
  contravvenire: ['contrav', 'venire'], rinvenire: ['rin', 'venire'], sovvenire: ['sov', 'venire'], addivenire: ['addi', 'venire'],
  sopravvenire: ['soprav', 'venire'], avvenire: ['av', 'venire'],
  sopravvivere: ['soprav', 'vivere'],
  possedere: ['pos', 'sedere'], soprassedere: ['sopras', 'sedere'],
  avvedersi: ['av', 'vedere'], intravedere: ['intra', 'vedere'], travedere: ['tra', 'vedere'],
  ravvedersi: ['rav', 'vedere'],
  avvincere: ['av', 'vincere'], stravincere: ['stra', 'vincere'], evincere: ['e', 'vincere'],
  rinchiudere: ['rin', 'chiudere'], racchiudere: ['rac', 'chiudere'], socchiudere: ['soc', 'chiudere'], schiudere: ['s', 'chiudere'], dischiudere: ['di', 'schiudere'],
  ammettere: ['am', 'mettere'],
  arrendersi: ['ar', 'rendere'],
  ascendere: ['a', 'scendere'], discendere: ['di', 'scendere'], condiscendere: ['condi', 'scendere'], trascendere: ['tra', 'scendere'],
  attendere: ['at', 'tendere'], intendere: ['in', 'tendere'], pretendere: ['pre', 'tendere'], stendere: ['s', 'tendere'], estendere: ['es', 'tendere'],
  distendere: ['dis', 'tendere'], contendere: ['con', 'tendere'], protendere: ['pro', 'tendere'], sottintendere: ['sottin', 'tendere'], fraintendere: ['frain', 'tendere'],
  ottendere: ['ot', 'tendere'],
  corrispondere: ['cor', 'rispondere'],
  confondere: ['con', 'fondere'], diffondere: ['dif', 'fondere'], infondere: ['in', 'fondere'], profondere: ['pro', 'fondere'], effondere: ['ef', 'fondere'], rifondere: ['ri', 'fondere'],
  ammorbidire: null,
  commuovere: ['com', 'muovere'], promuovere: ['pro', 'muovere'], rimuovere: ['ri', 'muovere'], smuovere: ['s', 'muovere'],
  riscuotere: ['ri', 'scuotere'],
  interrompere: ['inter', 'rompere'], corrompere: ['cor', 'rompere'], irrompere: ['ir', 'rompere'], prorompere: ['pro', 'rompere'], dirompere: ['di', 'rompere'], erompere: ['e', 'rompere'],
  accadere: ['ac', 'cadere'], decadere: ['de', 'cadere'], ricadere: ['ri', 'cadere'], scadere: ['s', 'cadere'],
  compiacere: ['com', 'piacere'], dispiacere: ['dis', 'piacere'], spiacere: ['s', 'piacere'],
  soggiacere: ['sog', 'giacere'],
  rinascere: ['ri', 'nascere'],
  riconoscere: ['ri', 'conoscere'], disconoscere: ['dis', 'conoscere'], misconoscere: ['mis', 'conoscere'],
  accrescere: ['ac', 'crescere'], decrescere: ['de', 'crescere'], rincrescere: ['rin', 'crescere'], ricrescere: ['ri', 'crescere'],
  convivere: ['con', 'vivere'], rivivere: ['ri', 'vivere'],
  descrivere: ['de', 'scrivere'], iscrivere: ['i', 'scrivere'], prescrivere: ['pre', 'scrivere'], sottoscrivere: ['sotto', 'scrivere'],
  trascrivere: ['tra', 'scrivere'], riscrivere: ['ri', 'scrivere'], circoscrivere: ['circo', 'scrivere'], ascrivere: ['a', 'scrivere'], proscrivere: ['pro', 'scrivere'],
  rileggere: ['ri', 'leggere'],
  equivalere: ['equi', 'valere'], prevalere: ['pre', 'valere'], rivalersi: ['ri', 'valere'],
  condolersi: ['con', 'dolere'],
  soffriggere: ['sof', 'friggere'],
  richiedere: ['ri', 'chiedere'],
  comprendere: ['com', 'prendere'], apprendere: ['ap', 'prendere'], sorprendere: ['sor', 'prendere'], riprendere: ['ri', 'prendere'],
  intraprendere: ['intra', 'prendere'], rapprendersi: ['rap', 'prendere'],
  smettere: ['s', 'mettere'], permettere: ['per', 'mettere'], promettere: ['pro', 'mettere'], commettere: ['com', 'mettere'], trasmettere: ['tras', 'mettere'],
  sottomettere: ['sotto', 'mettere'], omettere: ['o', 'mettere'], dimettere: ['di', 'mettere'], rimettere: ['ri', 'mettere'], emettere: ['e', 'mettere'],
  immettere: ['im', 'mettere'], premettere: ['pre', 'mettere'],
  percorrere: ['per', 'correre'], ricorrere: ['ri', 'correre'], trascorrere: ['tra', 'scorrere'], scorrere: ['s', 'correre'], concorrere: ['con', 'correre'],
  decorrere: ['de', 'correre'], incorrere: ['in', 'correre'], discorrere: ['di', 'scorrere'],
  riscoprire: ['ri', 'scoprire'], scoprire: ['s', 'coprire'], ricoprire: ['ri', 'coprire'], riaprire: ['ri', 'aprire'],
  assalire: ['as', 'salire'], risalire: ['ri', 'salire'],
  riapparire: ['ri', 'apparire'],
  divenire: ['di', 'venire'], convenire: ['con', 'venire'], intervenire: ['inter', 'venire'], prevenire: ['pre', 'venire'], provenire: ['pro', 'venire'],
  svenire: ['s', 'venire'], pervenire: ['per', 'venire'],
  ottenere: ['ot', 'tenere'], contenere: ['con', 'tenere'], sostenere: ['sos', 'tenere'], ritenere: ['ri', 'tenere'], detenere: ['de', 'tenere'], attenersi: ['at', 'tenere'],
  comporre: ['com', 'porre'], proporre: ['pro', 'porre'], imporre: ['im', 'porre'], disporre: ['dis', 'porre'], esporre: ['es', 'porre'], opporre: ['op', 'porre'],
  supporre: ['sup', 'porre'], deporre: ['de', 'porre'], posporre: ['pos', 'porre'], presupporre: ['presup', 'porre'], sovrapporre: ['sovrap', 'porre'],
  contrapporre: ['contrap', 'porre'], frapporre: ['frap', 'porre'], interporre: ['inter', 'porre'], anteporre: ['ante', 'porre'], riporre: ['ri', 'porre'],
  scomporre: ['scom', 'porre'], ricomporre: ['ricom', 'porre'], sottoporre: ['sotto', 'porre'], preporre: ['pre', 'porre'], apporre: ['ap', 'porre'],
  decomporre: ['decom', 'porre'], giustapporre: ['giustap', 'porre'], predisporre: ['predis', 'porre'], indisporre: ['indis', 'porre'], trasporre: ['tras', 'porre'],
  attrarre: ['at', 'trarre'], contrarre: ['con', 'trarre'], detrarre: ['de', 'trarre'], distrarre: ['dis', 'trarre'], estrarre: ['es', 'trarre'],
  protrarre: ['pro', 'trarre'], ritrarre: ['ri', 'trarre'], sottrarre: ['sot', 'trarre'], astrarre: ['as', 'trarre'],
  risorgere: ['ri', 'sorgere'], insorgere: ['in', 'sorgere'],
  sporgere: ['s', 'porgere'],
  cospargere: ['co', 'spargere'],
  convergere: ['con', 'vergere'],
  contorcere: ['con', 'torcere'], ritorcere: ['ri', 'torcere'], storcere: ['s', 'torcere'], estorcere: ['es', 'torcere'], distorcere: ['dis', 'torcere'],
  rivolgere: ['ri', 'volgere'], svolgere: ['s', 'volgere'], coinvolgere: ['coin', 'volgere'], avvolgere: ['av', 'volgere'], sconvolgere: ['scon', 'volgere'],
  stravolgere: ['stra', 'volgere'], travolgere: ['tra', 'volgere'], involgere: ['in', 'volgere'], capovolgere: ['capo', 'volgere'],
  convincere: ['con', 'vincere'],
  ridipingere: ['ri', 'dipingere'],
  disperdere: ['dis', 'perdere'], sperdere: ['s', 'perdere'],
  riaccendere: ['ri', 'accendere'],
  rinascondere: ['ri', 'nascondere'],
  ridiscutere: ['ri', 'discutere'],
  riprodursi: null,
};
