import assert from 'node:assert/strict';
import fs from 'node:fs';
import {loadPlaywright,launchBrowser,ensureServer,boot,gotoRoute,contextOptions} from './lib.mjs';
const {chromium,webkit,devices}=await loadPlaywright(),stop=await ensureServer(),browser=process.env.COURSE_BROWSER==='webkit'?await webkit.launch():await launchBrowser(chromium);
let context,page;const errors=[],results=[];
const check=async(name,fn)=>{await fn();results.push(name);console.log('PASS',name);};
async function fresh(width=430,height=932){await context?.close();context=await browser.newContext(contextOptions(devices['iPhone 13'],{viewport:{width,height},reducedMotion:'reduce'}));page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));await boot(page);await page.evaluate(async()=>{const {store}=await import('./js/store.js');store.setSetting('tts',false);});}
async function state(){return page.evaluate(async()=>{const {store}=await import('./js/store.js'),{grammarLesson,grammarProgress}=await import('./js/learning/grammar-course.js'),{currentCourseStep}=await import('./js/learning/course-v2-engine.js');const s=store.learning.session,l=grammarLesson(s.entryId);return {session:s,lesson:l,view:currentCourseStep(l,s),progress:grammarProgress(l,store.learning),events:Object.values(store.learning.events),completions:store.learning.completions,xp:store.current.stats.xp};});}
async function next(){await page.locator('[data-course-next]').click();}
async function answer(q,wrong=false){
 if(q.format==='choice')await page.locator(`[data-choice="${q.options.indexOf(wrong?q.options.find(v=>v!==q.answer):q.answer)}"]`).click();
 else if(q.format==='type'){await page.locator('[data-course-input]').fill(wrong?'xyz':q.answer);await page.locator('[data-check-course]').click();}
 else if(q.format==='order'){let rest=q.answer;const tokens=q.tokens.map((t,i)=>({t,i}));while(tokens.length){const n=tokens.findIndex(x=>rest.startsWith(x.t));assert(n>=0,q.id);const [{t,i}]=tokens.splice(n,1);await page.locator(`[data-token="${i}"]`).click();rest=rest.slice(t.length).trimStart();}await page.locator('[data-check-course]').click();}
 else {for(let i=0;i<q.pairs.length;i++){await page.locator(`[data-pair-left="${i}"]`).click();await page.locator(`[data-pair-right="${i}"]`).click();}}
}
async function seek(predicate){for(let i=0;i<150;i++){const s=await state();if(predicate(s))return s;if(s.view.kind==='question'&&!s.view.result)await answer(s.view.step);else if(s.view.kind==='complete'||s.view.kind==='exhausted')throw Error('Ended before requested step');else await next();}throw Error('Step not reached');}
async function finish(){return seek(s=>s.view.kind==='complete');}
// Seed a specific UI state for persistence/layout checks; teaching order has its own walkthrough.
async function fixture(kind){const id=await page.evaluate(async kind=>{const {store}=await import('./js/store.js'),{grammarCourse}=await import('./js/learning/grammar-course.js'),{createCourseSession}=await import('./js/learning/course-v2-engine.js');const l=grammarCourse.lessons.find(l=>l.steps.some(s=>kind==='reading'?s.kind==='question'&&s.stage==='independent'&&s.passageId:kind==='listening'?s.kind==='question'&&s.stage==='independent'&&s.audioId:kind==='speak'?s.kind==='portfolio'&&s.mode==='speak':s.kind===kind||s.kind==='question'&&s.format===kind));const n=l.steps.findIndex(s=>kind==='reading'?s.kind==='question'&&s.stage==='independent'&&s.passageId:kind==='listening'?s.kind==='question'&&s.stage==='independent'&&s.audioId:kind==='speak'?s.kind==='portfolio'&&s.mode==='speak':s.kind===kind||s.kind==='question'&&s.format===kind);const session=createCourseSession(l);session.courseV2.stepIndex=n;store.saveLearningSession(session);await store.saveNow();return l.id;},kind);await gotoRoute(page,'/learn/grammar/'+id);return state();}
try{
 await check('New learners start with meanings and models before the first supported check',async()=>{await fresh();await gotoRoute(page,'/learn');assert.match(await page.locator('.course-summary').innerText(),/Foundations/);await page.locator('.course-preview a').first().click();await page.waitForSelector('[data-course-lesson]');let s=await state();assert.equal(s.view.kind,'words');assert(s.view.step.words.every(w=>w.it&&w.en));assert.equal(s.events.length,0);await next();s=await state();assert.equal(s.view.kind,'teach');assert(s.view.step.examples.length);s=await seek(s=>s.view.kind==='question');assert.equal(s.view.step.stage,'guided');assert.equal(await page.locator('.course-guided-cue').count(),1);await answer(s.view.step);s=await state();assert(!s.progress.complete);assert(s.events.at(-1).grammarPhase==='guided');assert.equal(await page.locator('[data-feedback-state="correct"]').count(),1);const before=s.session.index;await page.waitForTimeout(250);assert.equal((await state()).session.index,before);});
 await check('Multiple independent contexts complete a lesson without checking off vocabulary',async()=>{const s=await finish();assert(s.progress.complete);assert(s.events.filter(e=>e.grammarPhase==='independent'&&e.ok).length>=2);assert.equal(Object.keys(s.completions).length,0);assert(s.events.some(e=>e.lessonFinished));assert.equal(await page.locator('[role="progressbar"]').getAttribute('aria-valuenow'),'100');await gotoRoute(page,'/course');assert.match(await page.locator('.course-summary').innerText(),/1 \/ \d+ grammar lessons completed/);});
 await check('An error gives feedback, a repair model, and a supported retry; Back cannot submit twice',async()=>{await fresh();const id=await page.evaluate(async()=>{const {grammarCourse}=await import('./js/learning/grammar-course.js');return grammarCourse.lessons[0].id;});await gotoRoute(page,'/learn/grammar/'+id);let s=await seek(s=>s.view.kind==='question'&&s.view.step.stage==='independent'&&s.view.step.format==='choice');await answer(s.view.step,true);s=await state();assert(!s.progress.complete);assert.equal(await page.locator('[data-feedback-state="incorrect"]').count(),1);await next();assert.equal((await state()).view.kind,'repair');const count=(await state()).events.length;await page.locator('[data-course-back]').click();assert.equal(await page.locator('[data-history="true"]').count(),1);assert.equal((await state()).events.length,count);assert.equal(await page.locator('[data-choice]:not(:disabled)').count(),0);await page.locator('[data-return-live]').click();await next();assert((await state()).view.guided);});
 await check('Saved typing drafts and shuffled choices survive reload without evidence or XP duplication',async()=>{await fresh();await fixture('type');await page.locator('[data-course-input]').fill('Una bozza');await page.evaluate(async()=>{const {store}=await import('./js/store.js');await store.saveNow();});const before=await state();await page.reload({waitUntil:'domcontentloaded'});await page.waitForSelector('[data-course-input]');assert.equal(await page.locator('[data-course-input]').inputValue(),'Una bozza');const after=await state();assert.deepEqual(after.events,before.events);assert.equal(after.xp,before.xp);assert.equal(after.view.step.id,before.view.step.id);});
 await check('Matching cards disappear only on a correct pair and errors are retained',async()=>{await fresh();let s=await fixture('match');await page.locator('[data-pair-left="0"]').click();await page.locator('[data-pair-right="1"]').click();s=await state();assert.equal(s.events.at(-1).outcome,'incorrect');assert.equal(s.session.courseV2.matched.length,0);assert.equal(s.view.result,null);await page.locator('[data-pair-left="0"]').click();await page.locator('[data-pair-right="0"]').click();assert.equal(await page.locator('[data-pair-left="0"]').getAttribute('disabled'),'');assert.deepEqual((await state()).session.courseV2.matched,[0]);});
 await check('Open work is saved for self-review and is never treated as a right or wrong answer',async()=>{await fresh();await fixture('portfolio');await page.locator('[data-portfolio-draft]').fill('La mia risposta personale.');await page.locator('[data-portfolio-model]').click();await page.locator('[data-rubric="0"]').check();await page.evaluate(async()=>{const {store}=await import('./js/store.js');await store.saveNow();});const before=await state();await page.reload({waitUntil:'domcontentloaded'});await page.waitForSelector('[data-portfolio-draft]');assert.equal(await page.locator('[data-portfolio-draft]').inputValue(),'La mia risposta personale.');assert.equal(await page.locator('[data-rubric="0"]').isChecked(),true);await next();assert.deepEqual((await state()).events,before.events);});
 await check('Source readings stay available beside their questions',async()=>{await fresh();const s=await fixture('reading');await page.locator('.course-reading-source summary').click();assert(await page.locator('.course-passage').innerText());await page.locator('[data-passage-translation]').click();await answer(s.view.step);assert((await state()).events.at(-1).assistance.includes('translation'));assert.equal((await state()).events.at(-1).grammarPhase,'independent');});
 await check('Listening checks cannot be credited by reading a transcript or with no played audio',async()=>{await fresh();let s=await fixture('listening');await page.locator('[data-transcript]').click();await answer(s.view.step);s=await state();assert(s.events.at(-1).assistance.includes('transcript'));});
 await check('Listening evidence requires completed playback of its source',async()=>{await fresh();const s=await fixture('listening');await page.locator('[data-course-audio]').evaluate(audio=>new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(Error('Audio playback timed out')),25000);audio.addEventListener('ended',()=>{clearTimeout(timer);resolve();},{once:true});audio.addEventListener('error',()=>{clearTimeout(timer);reject(Error('Audio failed'));},{once:true});audio.playbackRate=4;audio.play().catch(reject);}));assert((await state()).session.courseV2.audioPlayed.includes(s.view.step.audioId));await answer(s.view.step);const event=(await state()).events.at(-1);assert.equal(event.grammarPhase,'independent');assert.equal(event.modality,'listening');assert.equal(event.ok,true);assert.deepEqual(event.assistance,[]);});
 await check('The EN toggle exposes help without granting independent reading credit',async()=>{await fresh();const s=await fixture('reading');await page.locator('#enToggle').click();await answer(s.view.step);const event=(await state()).events.at(-1);assert(event.assistance.includes('translation'));assert.equal(event.grammarPhase,'independent');});
 await check('A prerequisite detour preserves a return to the interrupted lesson',async()=>{await fresh();const id=await page.evaluate(async()=>{const {grammarCourse}=await import('./js/learning/grammar-course.js');return grammarCourse.lessons.find(l=>l.prerequisites.length).id;});await gotoRoute(page,'/learn/grammar/'+id);await page.locator('.grammar-prerequisites summary').click();await page.locator('.grammar-prerequisites a').first().click();await page.waitForSelector('[data-course-lesson]');await page.locator('[data-pause]').click();await page.locator(`.grammar-footer a[href="#/learn/grammar/${id}"]`).click();await page.waitForSelector(`[data-course-lesson="${id}"]`);assert.equal((await state()).view.kind,'words');});
 await check('Skip retains unfinished skills and Pause/Resume preserves the current lesson',async()=>{await fresh();await fixture('choice');await page.locator('[data-defer]').click();let s=await state();assert(s.session.courseV2.deferred.length);assert(!s.progress.complete);await page.locator('[data-pause]').click();assert.equal(await page.locator('[data-resume]').count(),1);await page.reload({waitUntil:'domcontentloaded'});await page.waitForSelector('[data-resume]');await page.locator('[data-resume]').click();assert.equal((await state()).session.courseV2.paused,false);});
 await check('Placement gives a conservative suggestion without completing any lesson or awarding XP',async()=>{await fresh();await gotoRoute(page,'/course/placement');await page.locator('[data-begin]').click();for(let i=0;i<6;i++)await page.locator('[data-unknown]').click();assert.match(await page.locator('.grammar-finish').innerText(),/Start with Foundations/);const result=await page.evaluate(async()=>{const {store}=await import('./js/store.js');return {xp:store.current.stats.xp,completions:store.learning.completions,graded:Object.values(store.learning.events).filter(e=>e.outcome==='correct'||e.outcome==='incorrect').length};});assert.equal(result.xp,0);assert.deepEqual(result.completions,{});assert.equal(result.graded,0);});
 await check('B2 placement supports sentence ordering, reload, and a complete next-stage suggestion',async()=>{await fresh();await page.evaluate(async()=>{const {store}=await import('./js/store.js'),{grammarCourse}=await import('./js/learning/grammar-course.js'),{placementQuestions}=await import('./js/learning/course-v2-placement.js');store.saveLearningSession({id:'placement-b2-test',entryId:'course:placement',mode:'placement',createdAt:Date.now(),index:0,placement:{started:true,level:'B2',queue:placementQuestions(grammarCourse.lessons,'B2'),answers:[],history:[],draft:'',selected:null,assisted:false,finished:false}});await store.saveNow();});await gotoRoute(page,'/course/placement');for(let n=0;n<6;n++){const q=await page.evaluate(async()=>{const {store}=await import('./js/store.js'),{grammarLesson}=await import('./js/learning/grammar-course.js');const p=store.learning.session.placement,i=p.queue[p.answers.length];return grammarLesson(i.lessonId).steps.find(q=>q.id===i.questionId);});if(q.format==='choice')await page.locator(`[data-placement-choice="${q.options.indexOf(q.answer)}"]`).click();else if(q.format==='order'){let rest=q.answer;const tokens=q.tokens.map((t,i)=>({t,i}));while(tokens.length){const index=tokens.findIndex(x=>rest.startsWith(x.t));assert(index>=0);const [{t,i}]=tokens.splice(index,1);await page.locator(`[data-placement-token="${i}"]`).click();rest=rest.slice(t.length).trimStart();if(tokens.length===q.tokens.length-1){await page.reload({waitUntil:'domcontentloaded'});await page.waitForSelector('[data-placement-remove]');assert.equal(await page.locator('[data-placement-remove]').count(),1);}}}else await page.locator('[data-placement-input]').fill(q.answer);await page.locator('[data-answer]').click();}assert.match(await page.locator('.grammar-finish').innerText(),/Ready for a few more/);await page.locator('[data-more]').click();assert.match(await page.locator('.grammar-question .kicker').innerText(),/C1/);const r=await page.evaluate(async()=>{const {store}=await import('./js/store.js');return {xp:store.current.stats.xp,completions:store.learning.completions};});assert.equal(r.xp,0);assert.deepEqual(r.completions,{});});
 await check('An interrupted placement with no available questions returns a usable suggestion',async()=>{await fresh();await page.evaluate(async()=>{const {store}=await import('./js/store.js');store.saveLearningSession({id:'placement-empty-test',entryId:'course:placement',mode:'placement',createdAt:Date.now(),index:0,placement:{started:true,level:'B2',queue:[],answers:[],history:[],draft:'',selected:null,assisted:false,finished:false}});await store.saveNow();});await gotoRoute(page,'/course/placement');assert.match(await page.locator('.grammar-finish').innerText(),/tentative starting point/);await page.locator('[data-use]').click();await page.waitForSelector('.course-page');assert.match(await page.locator('.course-summary').innerText(),/B2/);});
 await check('Personal recordings are isolated by profile and removed on progress reset',async()=>{await fresh();const result=await page.evaluate(async()=>{const {store}=await import('./js/store.js'),{saveCourseRecording,getCourseRecording}=await import('./js/learning/course-v2-media.js');const owner=store.current.id,key=owner+'|test-recording';await saveCourseRecording(key,new Blob(['private audio'],{type:'audio/webm'}));const original=await (await getCourseRecording(key)).text();const second=await store.createProfile('Second learner');const other=await getCourseRecording(second.id+'|test-recording');await store.switchProfile(owner);await store.resetProgress();return {original,other:other||null,removed:!(await getCourseRecording(key))};});assert.equal(result.original,'private audio');assert.equal(result.other,null);assert(result.removed);});
 await check('A microphone response counts only after audio is saved, including navigation while it stops',async()=>{await fresh();await page.evaluate(()=>{Object.defineProperty(navigator.mediaDevices,'getUserMedia',{configurable:true,value:async()=>({getTracks:()=>[{stop(){}}]})});globalThis.MediaRecorder=class{constructor(){this.state='inactive';this.mimeType='audio/webm';}start(){this.state='recording';}stop(){this.state='inactive';setTimeout(()=>{this.ondataavailable?.({data:new Blob(['test recording'],{type:this.mimeType})});this.onstop?.();},150);}};});let s=await fixture('speak');const id=s.lesson.id,step=s.view.step.id;await page.locator('[data-record]').click();assert.equal((await state()).session.courseV2.portfolios[step].recording,undefined);await gotoRoute(page,'/course');await page.waitForTimeout(350);const saved=await page.evaluate(async({id,step})=>{const {store}=await import('./js/store.js'),{getCourseRecording}=await import('./js/learning/course-v2-media.js');const m=store.learning.sessions['g:'+id+'|lesson'].courseV2.portfolios[step].recording;return {metadata:m,text:m?await(await getCourseRecording(m.key)).text():null};},{id,step});assert(saved.metadata.bytes>0);assert.equal(saved.text,'test recording');assert.equal(await page.locator('.course-page').count(),1);await page.evaluate(async key=>{const {deleteCourseRecordings}=await import('./js/learning/course-v2-media.js');await deleteCourseRecordings(key,{exact:true});},saved.metadata.key);await gotoRoute(page,'/learn/grammar/'+id);await page.getByText('The audio is unavailable on this device.',{exact:false}).waitFor();assert.equal(await page.locator('.course-record-tools audio').count(),0);});
 await check('Feedback and Continue stay in the viewport at compact and large iPhone sizes',async()=>{for(const [w,h] of [[375,667],[430,932],[440,956]]){await fresh(w,h);const s=await fixture('choice');await answer(s.view.step);const layout=await page.evaluate(()=>({scroll:document.documentElement.scrollWidth,y:scrollY,footer:document.querySelector('.grammar-footer').getBoundingClientRect().toJSON(),next:document.querySelector('[data-course-next]').getBoundingClientRect().toJSON(),height:innerHeight}));assert(layout.scroll<=w+1);assert.equal(layout.y,0);assert(layout.next.top>=0&&layout.next.bottom<=layout.height+1);assert(Math.abs(layout.footer.bottom-layout.height)<2);await page.screenshot({path:`/tmp/parola-course-v2-${w}.png`});}});
 assert.deepEqual(errors,[]);console.log(`${results.length} v2 course browser checks passed.`);
}finally{fs.writeFileSync(new URL(`./report-course-v2${process.env.COURSE_BROWSER==='webkit'?'-webkit':''}.json`,import.meta.url),JSON.stringify({results,errors},null,2));await browser.close();stop();}
