import { COURSE_V2_LOOKUP_ENTRIES, COURSE_V2_LOOKUP_ALIASES, COURSE_V2_LOOKUP_FUNCTIONS, COURSE_V2_LOOKUP_NAMES, COURSE_V2_LOOKUP_FORM_NOTES } from './course-v2-glosses.js';

// Reviewed lookup-only additions for authored grammar examples and answer sentences.
// These are not learning entries. In particular, a standalone verb form below
// does not ask the conjugator to invent an unaudited full paradigm.
const noun = (it, en, g, pl, note = '') => ({
  id: `grammar:${it}|noun`, it, en, pos: 'noun', g, pl,
  lookupSource: 'curated', ...(note ? { note } : {}),
});
const adjective = (it, en, forms, note = '') => ({
  id: `grammar:${it}|adj`, it, en, pos: 'adj', forms,
  lookupSource: 'curated', ...(note ? { note } : {}),
});
const verbForm = (it, en, lemma, note) => ({
  id: `grammar:${it}|form`, it, en, pos: 'verb form',
  lookupSource: 'curated', note: `${note} Form of ${lemma}.`,
});

export const GRAMMAR_LOOKUP_ENTRIES = [
  ...COURSE_V2_LOOKUP_ENTRIES,
  noun('bus','bus','m','bus','Invariable noun: il bus, i bus.'),
  noun('flash','flash; camera flash','m','flash','Invariable noun.'),
  noun('lista','list','f','liste'),
  noun('organizzatrice','female organizer','f','organizzatrici'),
  adjective('civico','civic; municipal',['civico','civica','civici','civiche']),
  adjective('eventuale','possible; potential',['eventuale','eventuale','eventuali','eventuali']),
  adjective('intenso','intense',['intenso','intensa','intensi','intense']),
  adjective('interno','internal; inside',['interno','interna','interni','interne']),
  adjective('nominativo','issued in a named person’s name',['nominativo','nominativa','nominativi','nominative']),
  adjective('noto','known',['noto','nota','noti','note']),
  adjective('silenzioso','quiet; silent',['silenzioso','silenziosa','silenziosi','silenziose']),
  verbForm('modificare','to change; to edit','modificare','Infinitive'),
  verbForm('riprendono','they resume; they take up again','riprendere','Third-person plural present'),
  verbForm('scannerizzarlo','to scan it','scannerizzare','Infinitive scannerizzare + lo'),
  verbForm('verificheremo','we will check; we will verify','verificare','First-person plural future'),
  // Context vocabulary for the authored course, with attested forms only.
  noun("affermazione", "statement; claim", "f", "affermazioni"),
  noun("anticipo", "advance; being early", "m", "anticipi"),
  noun("autorizzazione", "authorization; permission", "f", "autorizzazioni"),
  noun("cagione", "cause; reason (literary)", "f", "cagioni"),
  noun("camion", "truck; lorry", "m", "camion"),
  noun("cavo", "cable", "m", "cavi"),
  noun("comitato", "committee", "m", "comitati"),
  noun("compagnia", "company; companionship", "f", "compagnie"),
  noun("conclusione", "conclusion", "f", "conclusioni"),
  noun("contenimento", "containment; restraint", "m", "contenimenti"),
  noun("cordoglio", "grief; sorrow", "m", "-"),
  noun("cortile", "courtyard", "m", "cortili"),
  noun("costume", "custom; habit; costume", "m", "costumi"),
  noun("descrizione", "description", "f", "descrizioni"),
  noun("discesa", "descent; decrease", "f", "discese"),
  noun("disgrazia", "misfortune", "f", "disgrazie"),
  noun("disgraziato", "unfortunate person; wretch", "m", "disgraziati"),
  noun("distribuzione", "distribution", "f", "distribuzioni"),
  noun("divieto", "prohibition; ban", "m", "divieti"),
  noun("fase", "phase; stage", "f", "fasi"),
  noun("forum", "forum", "m", "forum"),
  noun("interesse", "interest", "m", "interessi"),
  noun("intervistatrice", "female interviewer", "f", "intervistatrici"),
  noun("accesso", "access; entrance", "m", "accessi"),
  noun("agente", "agent; officer", "mf", "agenti"),
  noun("atto", "act; deed; document", "m", "atti"),
  noun("ispezione", "inspection", "f", "ispezioni"),
  noun("origine", "origin; beginning", "f", "origini"),
  noun("modifica", "change; modification", "f", "modifiche"),
  noun("partecipazione", "participation; involvement", "f", "partecipazioni"),
  noun("precisione", "precision; accuracy", "f", "-"),
  noun("programmazione", "planning; scheduling; programming", "f", "programmazioni"),
  noun("prudenza", "caution; prudence", "f", "-"),
  noun("registrazione", "recording; registration; entry in a record", "f", "registrazioni"),
  noun("residente", "resident", "mf", "residenti"),
  noun("resoconto", "account; report", "m", "resoconti"),
  noun("revisione", "review; revision", "f", "revisioni"),
  noun("riapertura", "reopening", "f", "riaperture"),
  noun("riferimento", "reference", "m", "riferimenti"),
  noun("rimozione", "removal", "f", "rimozioni"),
  noun("senno", "judgment; good sense", "m", "-"),
  noun("sequenza", "sequence", "f", "sequenze"),
  noun("sezione", "section", "f", "sezioni"),
  noun("soggetto", "subject", "m", "soggetti"),
  noun("supposizione", "supposition; assumption", "f", "supposizioni"),
  noun("suggerimento", "suggestion", "m", "suggerimenti"),
  noun("tecnico", "male technician; technical expert", "m", "tecnici"),
  noun("terreno", "ground; land; terrain", "m", "terreni"),
  noun("testimonianza", "testimony; account", "f", "testimonianze"),
  noun("versione", "version; account", "f", "versioni"),
  noun("visitatore", "male visitor", "m", "visitatori"),
  noun("estensione", "extension; extent", "f", "estensioni"),
  noun("vizio", "vice; bad habit; defect", "m", "vizi"),
  adjective("abbreviato","abbreviated; shortened",["abbreviato", "abbreviata", "abbreviati", "abbreviate"]),
  adjective("accessibile","accessible",["accessibile", "accessibile", "accessibili", "accessibili"]),
  adjective("attivo","active",["attivo", "attiva", "attivi", "attive"]),
  adjective("centrale","central; main",["centrale", "centrale", "centrali", "centrali"]),
  adjective("certo","certain; sure",["certo", "certa", "certi", "certe"]),
  adjective("comunale","municipal; local council",["comunale", "comunale", "comunali", "comunali"]),
  adjective("contrario","opposite; contrary",["contrario", "contraria", "contrari", "contrarie"]),
  adjective("doloroso","painful",["doloroso", "dolorosa", "dolorosi", "dolorose"]),
  adjective("eccessivo","excessive",["eccessivo", "eccessiva", "eccessivi", "eccessive"]),
  adjective("estivo","summer; relating to summer",["estivo", "estiva", "estivi", "estive"]),
  adjective("ferroviario","railway; rail",["ferroviario", "ferroviaria", "ferroviari", "ferroviarie"]),
  adjective("formale","formal",["formale", "formale", "formali", "formali"]),
  adjective("futuro","future",["futuro", "futura", "futuri", "future"]),
  adjective("genealogico","genealogical; relating to a family tree",["genealogico", "genealogica", "genealogici", "genealogiche"]),
  adjective("implicito","implicit; implied",["implicito", "implicita", "impliciti", "implicite"]),
  adjective("iniziale","initial; opening",["iniziale", "iniziale", "iniziali", "iniziali"]),
  adjective("atroce","atrocious; dreadful",["atroce", "atroce", "atroci", "atroci"]),
  adjective("lodevole","praiseworthy",["lodevole", "lodevole", "lodevoli", "lodevoli"]),
  adjective("personale","personal",["personale", "personale", "personali", "personali"]),
  adjective("presente","present",["presente", "presente", "presenti", "presenti"]),
  adjective("principale","main; principal",["principale", "principale", "principali", "principali"]),
  adjective("reale","real; actual",["reale", "reale", "reali", "reali"]),
  adjective("rivoluzionario","revolutionary",["rivoluzionario", "rivoluzionaria", "rivoluzionari", "rivoluzionarie"]),
  adjective("solo","alone; only",["solo", "sola", "soli", "sole"]),
  adjective("sonoro","relating to sound; audible",["sonoro", "sonora", "sonori", "sonore"]),
  adjective("storico","historical",["storico", "storica", "storici", "storiche"]),
  adjective("tecnico","technical",["tecnico", "tecnica", "tecnici", "tecniche"]),
  adjective("ufficiale","official",["ufficiale", "ufficiale", "ufficiali", "ufficiali"]),
  adjective("verificabile","verifiable",["verificabile", "verificabile", "verificabili", "verificabili"]),
  verbForm("accaduto", "happened; occurred", "accadere", "Past participle"),
  verbForm("accorciare", "to shorten", "accorciare", "Infinitive"),
  verbForm("anticipata", "brought forward; planned in advance", "anticipare", "Feminine singular past participle"),
  verbForm("avvenga", "may happen; may occur", "avvenire", "Present subjunctive, singular"),
  verbForm("catalogato", "catalogued", "catalogare", "Past participle"),
  verbForm("causato", "caused", "causare", "Past participle"),
  verbForm("cessare", "to cease; to stop", "cessare", "Infinitive"),
  verbForm("cita", "cites; quotes", "citare", "Third-person singular present"),
  verbForm("compiangermi", "to pity me", "compiangere", "Infinitive compiangere + mi"),
  verbForm("completata", "completed", "completare", "Feminine singular past participle"),
  verbForm("consultare", "to consult", "consultare", "Infinitive"),
  verbForm("distribuire", "to distribute", "distribuire", "Infinitive"),
  verbForm("distribuito", "distributed", "distribuire", "Past participle"),
  verbForm("documenta", "documents; records", "documentare", "Third-person singular present"),
  verbForm("documentati", "documented", "documentare", "Masculine plural past participle"),
  verbForm("effettuato", "carried out; made", "effettuare", "Past participle"),
  verbForm("elimina", "eliminates; removes", "eliminare", "Third-person singular present or tu imperative"),
  verbForm("ignoravo", "I did not know; I was unaware", "ignorare", "First-person singular imperfetto"),
  verbForm("impegnare", "to commit; to occupy", "impegnare", "Infinitive"),
  verbForm("include", "includes", "includere", "Third-person singular present"),
  verbForm("indignarsi", "to feel indignant", "indignarsi", "Reflexive infinitive"),
  verbForm("iniziare", "to begin; to start", "iniziare", "Infinitive"),
  verbForm("inventa", "invents; makes up", "inventare", "Third-person singular present or tu imperative"),
  verbForm("limita", "limits; restricts", "limitare", "Third-person singular present or tu imperative"),
  verbForm("narrarlo", "to tell it; to narrate it", "narrare", "Infinitive narrare + lo"),
  verbForm("par", "seems; appears (literary)", "parere", "Shortened third-person singular pare"),
  verbForm("pareva", "seemed; appeared", "parere", "Third-person singular imperfetto"),
  verbForm("preoccupa", "worries; concerns", "preoccupare", "Third-person singular present or tu imperative"),
  verbForm("quantifica", "quantifies; states an amount", "quantificare", "Third-person singular present or tu imperative"),
  verbForm("riaprirà", "will reopen", "riaprire", "Third-person singular future"),
  verbForm("riaprire", "to reopen", "riaprire", "Infinitive"),
  verbForm("riassume", "summarizes", "riassumere", "Third-person singular present"),
  verbForm("riformula", "rephrases; reformulates", "riformulare", "Third-person singular present or tu imperative"),
  verbForm("rimosso", "removed", "rimuovere", "Past participle"),
  verbForm("segnala", "reports; points out", "segnalare", "Third-person singular present or tu imperative"),
  verbForm("socchiudevo", "I half-closed; I narrowed", "socchiudere", "First-person singular imperfetto"),
  verbForm("stringevo", "I tightened; I drew together", "stringere", "First-person singular imperfetto; mi stringevo nelle spalle means I shrugged"),
  verbForm("verificare", "to verify; to check", "verificare", "Infinitive"),
  noun('copia', 'copy', 'f', 'copie'),
  noun('guardaroba', 'cloakroom; wardrobe', 'm', 'guardaroba', 'An invariant noun: il guardaroba, i guardaroba.'),
  noun('zuppa', 'soup', 'f', 'zuppe'),
  noun('richiesta', 'request; application', 'f', 'richieste'),
  noun('chiarezza', 'clarity', 'f', '-', 'A quality normally used as a mass noun in this sense.'),
  noun('servizio', 'service', 'm', 'servizi'),
  noun('cautela', 'caution; care', 'f', '-', 'In this sense caution is normally a mass noun; cautele can mean precautions.'),
  noun('chiusura', 'closure; closing', 'f', 'chiusure'),
  noun('raccolta', 'collection; gathering', 'f', 'raccolte'),
  noun('segreteria', 'office; secretariat', 'f', 'segreterie'),
  noun('tabellone', 'display board; scoreboard', 'm', 'tabelloni'),
  noun('partecipante', 'participant', 'mf', 'partecipanti', 'The same noun form serves both genders; the article shows the gender.'),
  noun('regno', 'kingdom; realm', 'm', 'regni', 'Capitalized in the historical name Regno d’Italia.'),
  noun('messaggero', 'messenger', 'm', 'messaggeri'),
  noun('apertura', 'opening; opening time', 'f', 'aperture'),
  adjective('necessario', 'necessary', ['necessario', 'necessaria', 'necessari', 'necessarie']),
  adjective('rapido', 'fast; quick', ['rapido', 'rapida', 'rapidi', 'rapide']),
  adjective('incompleto', 'incomplete', ['incompleto', 'incompleta', 'incompleti', 'incomplete']),
  adjective('antico', 'ancient; old', ['antico', 'antica', 'antichi', 'antiche']),
  adjective('breve', 'short; brief', ['breve', 'breve', 'brevi', 'brevi']),
  adjective('fermo', 'still; stationary; stopped', ['fermo', 'ferma', 'fermi', 'ferme']),
  adjective('corretto', 'correct', ['corretto', 'corretta', 'corretti', 'corrette']),
  adjective('assente', 'absent', ['assente', 'assente', 'assenti', 'assenti']),
  adjective('nascosto', 'hidden', ['nascosto', 'nascosta', 'nascosti', 'nascoste']),
  adjective('atteso', 'expected; awaited', ['atteso', 'attesa', 'attesi', 'attese']),
  // Each missing lexical verb is represented by an attested form only. There
  // is no grammar course need to display unattested persons or tenses here.
  verbForm('iniziata', 'begun; started (feminine singular)', 'iniziare', 'Feminine singular past participle.'),
  verbForm('squillato', 'rung', 'squillare', 'Past participle.'),
  verbForm('inizia', 'he/she/it begins; starts', 'iniziare', 'Third-person singular present indicative.'),
  verbForm('iniziato', 'begun; started', 'iniziare', 'Past participle.'),
  verbForm('iniziò', 'he/she/it began', 'iniziare', 'Third-person singular passato remoto.'),
  verbForm('terminato', 'finished; completed', 'terminare', 'Past participle.'),
  verbForm('terminata', 'finished; completed (feminine singular)', 'terminare', 'Feminine singular past participle.'),
  verbForm('inaugurato', 'inaugurated; opened officially', 'inaugurare', 'Past participle.'),
  verbForm('esaminate', 'examined; reviewed (feminine plural)', 'esaminare', 'Feminine plural past participle.'),
  verbForm('esaminato', 'examined; reviewed', 'esaminare', 'Past participle.'),
  verbForm('applaudì', 'he/she applauded', 'applaudire', 'Third-person singular passato remoto.'),
  verbForm('squillò', 'it rang', 'squillare', 'Third-person singular passato remoto.'),
  verbForm('ripreso', 'resumed; started again', 'riprendere', 'Past participle.'),
  verbForm('proclamò', 'he/she/it proclaimed', 'proclamare', 'Third-person singular passato remoto.'),
  verbForm('rivisto', 'reviewed; revised', 'rivedere', 'Past participle.'),
  verbForm('deviare', 'to detour; to change course', 'deviare', 'Infinitive.'),
  verbForm('deviamo', 'we detour; we change course', 'deviare', 'First-person plural present indicative.'),
  verbForm('avvenuta', 'happened; occurred (feminine singular)', 'avvenire', 'Feminine singular past participle.'),
  verbForm('puntiamo', 'we aim', 'puntare', 'First-person plural present indicative.'),
  verbForm('informare', 'to inform', 'informare', 'Infinitive.'),
];

// An alias is attached only to an existing catalog lemma. This is an explicit
// attestation of the surface form, not a suffix rule or extra conjugation.
export const GRAMMAR_LOOKUP_ALIASES = {
  provare:['provarlo'],
  trattare:["trattarla"],
  stabilire:["stabilita"],
  ricevere:["riceverne"],
  osservare:["osservata", "osservati"],
  ipotizzare:["ipotizzata"],
  destinare:["destinata"],
  consentire:["consentita"],
  concludere:["conclusa"],
  compiere:["compiuta"],
  avvertire:["avvertirlo"],
  annunciare:["annunciata"],
  aspettare:['aspettami','aspettarla','aspettarci'], chiedere:['chiederlo'], controllare:['controllati'],
  incontrare:['incontrarci'], portare:['portamele'], richiamare:['richiamarla','richiamarmi'],
  rimandare:['rimandata'], ritirare:['ritirarlo'], trovare:['trovarli','trovata'],
  leggere: ['leggerlo','leggerle','leggerla','leggendolo','letta'], vedere: ['vederlo'], dare: ['darmi'],
  prendere: ['prenderlo'], comprare: ['comprati'], conoscere: ['conosciuti'],
  dire:['dimmi'], chiamare: ['chiamami','chiamarla','chiamarlo'], scrivere: ['scritte', 'scritta','scrivigli'], aiutare: ['aiutarti','aiutarmi'],
  nascondere: ['nascosta'], discutere: ['discussa'], superare: ['superata'],
  rinviare: ['rinviata'], prevedere: ['prevista'], avvisare: ['avvisateci','avvisarmi','avvisala','avvisarla','avvisarti','avvisatemi'],
  notare: ['notarlo'], comunicare: ['comunicata'], risolvere: ['risolverlo', 'risolti'],
  confermare: ['confermarmi', 'confermata'], indicare: ['indicarmi'], inviare: ['inviarmi'],
  mandare: ['mandami','mandamelo','mandarlo','mandarglielo'], potere: ['poter'], avere: ['averlo'],
  comodo: ['comodissime'], buono: ['buonissime'], bello: ['bellissima'],
};

for (const [lemma, aliases] of Object.entries(COURSE_V2_LOOKUP_ALIASES)) {
  GRAMMAR_LOOKUP_ALIASES[lemma] = [...new Set([...(GRAMMAR_LOOKUP_ALIASES[lemma] || []), ...aliases])];
}

// The singular lemma is already in the catalog, but its note explicitly
// records le colleghe. Supply that attested feminine plural to the local
// lookup copy so the popover can say la collega / le colleghe.
export const GRAMMAR_LOOKUP_ENTRY_PATCHES = {
  'w:collega|noun': { fem: 'collega', femPl: 'colleghe' },
};

export const GRAMMAR_LOOKUP_FUNCTIONS = [
  ...COURSE_V2_LOOKUP_FUNCTIONS,
  ['accanto','adv','beside; next door (accanto a: next to)'],
  ['materialmente','adv','physically; in actual practice'],
  ['quarantadue','num','forty-two'],
  ["assai", "adv", "very; much (often literary)"],
  ["ch’io", "conj", "that I; literary contraction of che io"],
  ["ciascun", "det", "each; every (masculine before a noun)"],
  ["ciascuna", "det", "each; every (feminine)"],
  ["dapprima", "adv", "at first; initially"],
  ["de’", "prep", "of the; literary form of dei"],
  ["ebbene", "interj", "well; then"],
  ["necessariamente", "adv", "necessarily"],
  ["propriamente", "adv", "properly; exactly; strictly speaking"],
  ["qualmente", "adv", "how; that (literary or archaic)"],
  ["sé", "pron", "himself; herself; itself; oneself"],
  ["soltanto", "adv", "only"],
  ["tutt’a", "adv", "part of tutt’a un tratto: all at once; suddenly"],
  ["veramente", "adv", "really; truly"],
  ["centoventi", "num", "one hundred and twenty"],
  ["settantotto", "num", "seventy-eight"],
  ["n", "word", "abbreviation n. means numero: number"],

  ['glielo','pron','it (masculine) to him, her, them, or polite you; gli/le + lo'],
  ['fino', 'prep', 'until; up to (often followed by a)'],
  ["po'", 'adv', 'a little; a bit (short for poco, often in un po’ di)'],
  ['gliela', 'pron', 'to him, her, or them + her or it (feminine singular direct object)'],
  ['quante', 'det', 'how many (feminine plural)'],
  ['quanti', 'det', 'how many (masculine plural)'],
  ['quali', 'pron', 'who; which (plural relative or interrogative)'],
  ['pur', 'conj', 'although; even though (before a gerund)'],
  ['troppe', 'det', 'too many (feminine plural)'],
];

export const GRAMMAR_LOOKUP_NAMES = [...COURSE_V2_LOOKUP_NAMES, 'Eva', 'Marta', 'Lucia', 'Elena', 'Laura', 'Elisa', 'Lia', 'Ada', 'Bruno', 'Nadia', 'Mattia', 'Pascal'];
export const GRAMMAR_LOOKUP_PLACES = [['piemonte', 'Piedmont'],['como','Como'],['genova','Genoa']];

// `lemma` confines each form note to the linked lexical candidate. Bare
// homographs therefore do not inherit a misleading grammatical explanation.
export const GRAMMAR_LOOKUP_FORM_NOTES = [
  ...COURSE_V2_LOOKUP_FORM_NOTES,
  {lemma:'aiutare',form:'aiutarmi',note:'Aiutare + mi: to help me.'},
  {lemma:'aspettare',form:'aspettarci',note:'Aspettare + ci: to wait for us.'},
  {lemma:'avvisare',form:'avvisala',note:'Familiar command avvisa + la: let her know.'},
  {lemma:'avvisare',form:'avvisarla',note:'Avvisare + la: to notify her or polite you.'},
  {lemma:'avvisare',form:'avvisarti',note:'Avvisare + ti: to let you know.'},
  {lemma:'avvisare',form:'avvisatemi',note:'Plural command avvisate + mi: let me know.'},
  {lemma:'leggere',form:'leggerla',note:'Leggere + la: to read it (feminine object).'},
  {lemma:'leggere',form:'leggendolo',note:'Gerund leggendo + lo: while reading it.'},
  {lemma:'leggere',form:'letta',note:'Feminine singular past participle of leggere.'},
  {lemma:'mandare',form:'mandarglielo',note:'Mandare + glie + lo: to send it to him, her, them or polite you.'},
  {lemma:'provare',form:'provarlo',note:'Provare + lo: to try it.'},
  {lemma:'richiamare',form:'richiamarmi',note:'Richiamare + mi: to call me back.'},
  {lemma:'scrivere',form:'scrivigli',note:'Familiar command scrivi + gli: write to him or them.'},
  { lemma: 'leggere', form: 'leggerlo', note: 'Leggere + lo: to read it; lo is an attached masculine singular direct-object pronoun.' },
  { lemma: 'vedere', form: 'vederlo', note: 'Vedere + lo: to see it; the final -e of the infinitive drops before lo.' },
  { lemma: 'dare', form: 'darmi', note: 'Dare + mi: to give me; the final -e of the infinitive drops before mi.' },
  { lemma: 'prendere', form: 'prenderlo', note: 'Prendere + lo: to take it; the final -e of the infinitive drops before lo.' },
  { lemma: 'comprare', form: 'comprati', note: 'Masculine plural past participle of comprare; it can agree with a counted object after ne.' },
  { lemma: 'conoscere', form: 'conosciuti', note: 'Masculine plural past participle of conoscere.' },
  { lemma: 'chiamare', form: 'chiamami', note: 'Familiar singular command chiama + mi: call me.' },
  { lemma: 'scrivere', form: 'scritte', note: 'Feminine plural past participle of scrivere.' },
  { lemma: 'scrivere', form: 'scritta', note: 'Feminine singular past participle of scrivere.' },
  { lemma: 'aiutare', form: 'aiutarti', note: 'Aiutare + ti: to help you.' },
  { lemma: 'nascondere', form: 'nascosta', note: 'Feminine singular past participle of nascondere; also used adjectivally for hidden.' },
  { lemma: 'discutere', form: 'discussa', note: 'Feminine singular past participle of discutere.' },
  { lemma: 'superare', form: 'superata', note: 'Feminine singular past participle of superare.' },
  { lemma: 'rinviare', form: 'rinviata', note: 'Feminine singular past participle of rinviare.' },
  { lemma: 'prevedere', form: 'prevista', note: 'Feminine singular past participle of prevedere: scheduled or expected.' },
  { lemma: 'avvisare', form: 'avvisateci', note: 'Plural command avvisate + ci: inform us.' },
  { lemma: 'notare', form: 'notarlo', note: 'Notare + lo: to notice it.' },
  { lemma: 'comunicare', form: 'comunicata', note: 'Feminine singular past participle of comunicare.' },
  { lemma: 'risolvere', form: 'risolverlo', note: 'Risolvere + lo: to solve it.' },
  { lemma: 'confermare', form: 'confermarmi', note: 'Confermare + mi: to confirm to me.' },
  { lemma: 'indicare', form: 'indicarmi', note: 'Indicare + mi: to tell or indicate to me.' },
  { lemma: 'inviare', form: 'inviarmi', note: 'Inviare + mi: to send to me.' },
  { lemma: 'mandare', form: 'mandami', note: 'Familiar singular command manda + mi: send me.' },
  { lemma: 'potere', form: 'poter', note: 'Poter is a shortened infinitive of potere before another infinitive.' },
  { lemma: 'avere', form: 'averlo', note: 'Avere + lo: to have it; lo attaches to the shortened infinitive aver.' },
  { lemma: 'comodo', form: 'comodissime', note: 'Feminine plural absolute superlative: extremely comfortable.' },
  { lemma: 'buono', form: 'buonissime', note: 'Feminine plural absolute superlative: extremely good.' },
  { lemma: 'bello', form: 'bellissima', note: 'Feminine singular absolute superlative: extremely beautiful.' },
];
