// Lookup-only support for reviewed verb examples (initial audited gap slice 0–179).
// These are lexical glosses, not new graded vocabulary or generated paradigms.
const noun=(it,en,g,pl,note='')=>({id:`verb:${it}|noun`,it,en,pos:'noun',g,pl,lookupSource:'curated',...(note?{note}:{})});
const adjective=(it,en,forms,note='')=>({id:`verb:${it}|adj`,it,en,pos:'adj',forms,lookupSource:'curated',...(note?{note}:{})});
export const VERB_LOOKUP_ENTRIES = [
  ...[
    ['pistacchio','pistachio','m','pistacchi'],
    ['tavola','table, especially for eating','f','tavole'],
    ['fronte','forehead','f','fronti'],
    ['tango','tango','m','tanghi'],
    ['favore','favour; help','m','favori'],
    ['sigaretta','cigarette','f','sigarette'],
    ['pipa','pipe for smoking','f','pipe'],
    ['vocale','vowel','f','vocali'],
    ['dimenticanza','lapse of memory; oversight','f','dimenticanze'],
    ['campanello','doorbell; small bell','m','campanelli'],
    ['calice','goblet; wine glass','m','calici'],
    ['scooter','scooter','m','scooter'],
    ['furgone','van','m','furgoni'],
    ['salsa','sauce','f','salse'],
    ['pulsante','button; switch','m','pulsanti'],
    ['oliva','olive','f','olive'],
    ['sugo','pasta sauce','m','sughi'],
    ['telo','sheet of cloth; cover','m','teli'],
    ['mensola','shelf','f','mensole'],
    ['vaso','pot; vase','m','vasi'],
    ['Capodanno','New Year’s Day; New Year','m','Capodanni'],
    ['ciliegio','cherry tree','m','ciliegi'],
    ['regime','rate; operating level; regime','m','regimi'],
    ['folla','crowd','f','folle'],
    ['cartellone','poster board; large poster','m','cartelloni'],
    ['sasso','stone; pebble','m','sassi'],
    ['frisbee','flying disc; Frisbee','m','frisbee'],
    ['ciotola','bowl','f','ciotole'],
    ['corridoio','corridor','m','corridoi'],
    ['aneddoto','anecdote','m','aneddoti'],
    ['palco','stage','m','palchi'],
    ['categoria','category','f','categorie'],
    ['sincerità','sincerity','f','-'],
    ['commessa','shop assistant (woman)','f','commesse'],
    ['legna','firewood','f','-'],
    ['piano','plan; floor; level','m','piani'],
    ['malinteso','misunderstanding','m','malintesi'],
    ['bersaglio','target','m','bersagli'],
    ['invitato','guest; invited person','m','invitati'],
    ['confine','border; boundary','m','confini'],
    ['procedimento','procedure; process','m','procedimenti'],
    ['organizzazione','organisation','f','organizzazioni'],
    ['diffusione','spread; dissemination','f','diffusioni'],
    ['codice','code','m','codici'],
    ['sciocchezza','silly thing; trifle','f','sciocchezze'],
    ['punizione','punishment','f','punizioni'],
    ['premio','prize; award','m','premi'],
    ['ringraziamento','thanks; expression of gratitude','m','ringraziamenti'],
    ['comando','command; instruction','m','comandi'],
    ['componente','component; member','mf','componenti'],
    ['cima','summit; top','f','cime'],
    ['provocazione','provocation','f','provocazioni'],
    ['disservizio','service failure; disruption','m','disservizi'],
    ['privilegio','privilege','m','privilegi'],
    ['controversia','dispute; controversy','f','controversie'],
    ['esperto','expert','m','esperti'],
    ['pozzanghera','puddle','f','pozzanghere'],
    ['muretto','low wall','m','muretti'],
    ['rivale','rival','mf','rivali'],
    ['concorrente','competitor','mf','concorrenti'],
    ['scusa','excuse; apology','f','scuse'],
    ['ciclista','cyclist','mf','ciclisti'],
    ['reputazione','reputation','f','reputazioni'],
    ['lacrima','tear','f','lacrime'],
    ['procedura','procedure','f','procedure'],
    ['riconoscimento','recognition; award','m','riconoscimenti'],
    ['complimento','compliment','m','complimenti'],
    ['odore','smell; odour','m','odori'],
    ['boccone','mouthful; bite','m','bocconi'],
    ['ingenuità','naivety','f','-'],
    ['frutto','fruit; result','m','frutti'],
    ['titolo','title; qualification','m','titoli'],
    ['onorificenza','honour; decoration','f','onorificenze'],
    ['router','router','m','router'],
    ['aggressione','assault; attack','f','aggressioni'],
    ['irregolarità','irregularity','f','irregolarità'],
    ['vassoio','tray','m','vassoi'],
    ['strategia','strategy','f','strategie'],
    ['direttiva','directive','f','direttive'],
    ['collaborazione','cooperation; collaboration','f','collaborazioni'],
    ['metallo','metal','m','metalli'],
    ['cera','wax','f','cere'],
    ['supporto','support','m','supporti'],
    ['figura','figure; shape','f','figure'],
    ['dialogo','dialogue','m','dialoghi'],
    ['territorio','territory; area','m','territori'],
    ['scenario','scenario','m','scenari'],
    ['tensione','tension','f','tensioni'],
    ['scogliera','cliff; rocky coast','f','scogliere'],
    ['provenienza','origin; provenance','f','provenienze'],
    ['memoria','memory','f','memorie'],
    ['assemblea','assembly; meeting','f','assemblee'],
    ['sostegno','support; assistance','m','sostegni'],
    ['preparativo','preparation','m','preparativi'],
    ['ricambio','replacement part','m','ricambi'],
    ['impulso','impulse','m','impulsi'],
    ['attacco','attack','m','attacchi'],
    ['orizzonte','horizon','m','orizzonti'],
    ['inseguitore','pursuer','m','inseguitori'],
    ['cattura','capture','f','catture'],
    ['chiarimento','clarification','m','chiarimenti'],
    ['villaggio','village','m','villaggi'],
    ['corda','rope','f','corde'],
    ['filo','thread; wire','m','fili'],
    ['vigilanza','supervision; vigilance','f','-'],
    ['legislatore','legislator','m','legislatori'],
    ['pretesto','pretext; excuse','m','pretesti'],
    ['tregua','truce','f','tregue'],
    ['complice','accomplice','mf','complici'],
    ['bancone','counter','m','banconi'],
    ['divergenza','difference; disagreement','f','divergenze'],
    ['veto','veto','m','veti'],
    ['statuto','statute; articles of association','m','statuti'],
    ['capriccio','whim; tantrum','m','capricci'],
    ['coordinatore','coordinator','m','coordinatori'],
    ['alcolico','alcoholic drink','m','alcolici'],
    ['piantina','young plant; seedling','f','piantine'],
    ['autenticità','authenticity','f','-'],
    ['conformità','compliance; conformity','f','-'],
    ['ricostruzione','reconstruction; account of events','f','ricostruzioni'],
    ['stesura','drafting; written draft','f','stesure'],
    ['lacuna','gap; omission','f','lacune'],
  ].map(([it,en,g,pl])=>noun(it,en,g,pl)),
  adjective('elogiativo','praising; complimentary',['elogiativo','elogiativa','elogiativi','elogiative']),
  adjective('amato','beloved',['amato','amata','amati','amate']),
  adjective('elettrico','electric',['elettrico','elettrica','elettrici','elettriche']),
  adjective('aromatico','aromatic',['aromatico','aromatica','aromatici','aromatiche']),
  adjective('elettronico','electronic',['elettronico','elettronica','elettronici','elettroniche']),
  adjective('costiero','coastal',['costiero','costiera','costieri','costiere']),
  adjective('radiofonico','radio; relating to radio',['radiofonico','radiofonica','radiofonici','radiofoniche']),
  adjective('sanitario','healthcare; medical',['sanitario','sanitaria','sanitari','sanitarie']),
  adjective('contrattuale','contractual',['contrattuale','contrattuale','contrattuali','contrattuali']),
  adjective('falso','false',['falso','falsa','falsi','false']),
  adjective('decisivo','decisive',['decisivo','decisiva','decisivi','decisive']),
  adjective('amministrativo','administrative',['amministrativo','amministrativa','amministrativi','amministrative']),
  adjective('inatteso','unexpected',['inatteso','inattesa','inattesi','inattese']),
  adjective('franco','free; frank; in farla franca: to get away with it',['franco','franca','franchi','franche']),
  adjective('esatto','exact; correct',['esatto','esatta','esatti','esatte']),
  adjective('culturale','cultural',['culturale','culturale','culturali','culturali']),
  adjective('esterno','external; outer',['esterno','esterna','esterni','esterne']),
  adjective('proprio','one’s own',['proprio','propria','propri','proprie']),
  adjective('elettorale','electoral',['elettorale','elettorale','elettorali','elettorali']),
  adjective('estero','foreign',['estero','estera','esteri','estere']),
  adjective('burocratico','bureaucratic',['burocratico','burocratica','burocratici','burocratiche']),
  adjective('fotografico','photographic',['fotografico','fotografica','fotografici','fotografiche']),
  adjective('espositivo','exhibition; display',['espositivo','espositiva','espositivi','espositive']),
  adjective('avversario','opposing; rival',['avversario','avversaria','avversari','avversarie']),
  adjective('commerciale','commercial',['commerciale','commerciale','commerciali','commerciali']),
  adjective('previsto','planned; expected; provided for',['previsto','prevista','previsti','previste']),
  adjective('documentato','documented; supported by evidence',['documentato','documentata','documentati','documentate']),
];

// Attested attached forms; do not infer these for unrelated verbs.
export const VERB_LOOKUP_ALIASES = {
  alzarsi:['alzarmi'], volere:['volerlo'], accorgersi:['accorgermene'],
  fare:['farsi'], conoscere:['conosciuta'], inventare:['inventata'],
};
export const VERB_LOOKUP_FUNCTIONS = [
  ['profondamente','adv','deeply'], ['pochissimo','adv','very little; for a very short time'],
  ['troppi','det','too many (masculine plural)'], ['troppa','det','too much (feminine singular)'],
  ["all’indietro",'adv','backwards'], ["dall’estero",'phrase','from abroad'],
  ["all’evidenza",'phrase','to the evidence; to what is obvious'],
  ["un’organizzazione",'phrase','an organisation; un’ + organizzazione'],
  ["l’odore",'phrase','the smell; l’ + odore'],
  ["un’onorificenza",'phrase','an honour; un’ + onorificenza'],
  ["un’aggressione",'phrase','an assault; un’ + aggressione'],
  ["un’irregolarità",'phrase','an irregularity; un’ + irregolarità'],
  ["l’assemblea",'phrase','the assembly; l’ + assemblea'],
  ["all’orizzonte",'phrase','on the horizon; a + l’orizzonte'],
  ["l’autenticità",'phrase','the authenticity; l’ + autenticità'],
  ['rapidamente','adv','quickly'], ['stavolta','adv','this time'],
  ['indietro','adv','back; backwards'], ['giù','adv','down; below'],
];
export const VERB_LOOKUP_NAMES = ['Milan'];
export const VERB_LOOKUP_PLACES = [
  ['alpi','Alps'],['spagna','Spain'],['brasile','Brazil'],
  ['francia','France'],['canada','Canada'],['svizzera','Switzerland'],
];
