import {html,raw,icon,toast} from '../ui.js';
import {setTitle,setChrome,captureViewOwnership} from '../app.js';
import {store} from '../store.js';
import {loadGrammarCourse,loadGrammarStage,grammarLesson,grammarHref} from '../learning/grammar-course.js';
import {grammarCourse} from '../learning/grammar-course.js';
import {placementQuestions,placementRecommendation,assessPlacement} from '../learning/course-v2-placement.js';
import {shuffle} from '../data.js';
import {createSentencePanel} from '../learning/sentence-panel.js';
import {mountActivityViewport} from '../learning/activity-viewport.js';
export async function render(root){
 const owned=captureViewOwnership(root);let disposed=false;
 const alive=()=>!disposed&&owned();
 await loadGrammarCourse();if(!alive())return;setTitle('Find your starting point');setChrome({tabs:false,back:false});
 const old=store.learning.sessions['course:placement|placement'];
 let session=old&&!old.placement.finished?JSON.parse(JSON.stringify(old)):{id:'placement:'+Date.now(),entryId:'course:placement',mode:'placement',createdAt:Date.now(),index:0,placement:{started:false,level:'A1',queue:[],answers:[],history:[],draft:'',selected:null,assisted:false,finished:false}};
 const p=()=>session.placement,save=()=>{if(alive()){session.updatedAt=Date.now();store.saveLearningSession(session);}};
 const item=()=>p().queue[p().answers.length],lesson=()=>grammarLesson(item()?.lessonId),question=()=>lesson()?.steps.find(s=>s.id===item()?.questionId);
 const panel=createSentencePanel(root,{onReveal:()=>{if(!alive())return;p().assisted=true;save();}});
 const viewport=mountActivityViewport(root,{panelSelector:'.grammar-scroll'});
 async function begin(level){if(!alive())return;await loadGrammarStage(level);if(!alive())return;delete p().suggestion;p().started=true;p().level=level;p().queue=placementQuestions(grammarCourse.lessons,level);p().answers=[];p().selected=null;p().draft='';p().tokens=[];p().order=null;p().assisted=false;if(!p().queue.length){finish(true);return;}save();draw();}
 function finish(stopped=false){if(!alive())return;p().history.push({level:p().level,answers:p().answers});const suggestion=placementRecommendation(p().level,p().answers,{stopped});p().suggestion=suggestion;p().finished=!suggestion.continueAt;save();draw();}
 function draw(){
  if(!alive())return;
  let body='',footer='';const q=question(),l=lesson();
  if(!p().started){body=html`<section class="grammar-teach"><span class="kicker">Optional · your pace</span><h1>Already know some Italian?</h1><p class="grammar-body">Try six short checks at a time. We’ll suggest where to begin from your grammar and reading answers. Use “I don’t know” whenever you need it.</p><p>This does not complete lessons, assess speaking or listening, or award a CEFR level. You can stop at any time and choose your own starting point.</p></section>`;footer='<button class="btn primary block" data-begin>Find my starting point</button><a class="btn ghost block" href="#/course">Start from zero or browse the course</a>';}
  else if(p().suggestion){const r=p().suggestion;body=html`<section class="grammar-finish"><span class="kicker">A starting suggestion</span><h1>${r.continueAt?'Ready for a few more?':`Start with ${r.level}`}</h1><p>${r.continueAt?'Those familiar patterns look comfortable. You can try the next set, or begin learning here.':r.uncertain?'You stopped before a full set. This is a tentative starting point.':'This stage gives you a place to build on the patterns you know and practise the less familiar ones.'}</p><p>Your earlier progress is unchanged. Placement does not mark any lesson or verb form learned.</p></section>`;footer=html`${r.continueAt?raw('<button class="btn primary block" data-more>Try the next set</button>'):''}<button class="btn ${r.continueAt?'secondary':'primary'} block" data-use>Begin at ${r.level||r.continueAt}</button><a class="btn ghost block" href="#/course">Choose another starting point</a>`;}
  else if(p().pending){
   const pending=p().pending;
   body=html`<section class="grammar-question"><span class="kicker">Accent restored</span><h1>Your answer</h1><label for="placement-answer">Written Italian</label><input id="placement-answer" readonly value="${pending.submission.displayText}" lang="it"><details><summary>As typed</summary><p>${pending.submission.originalText}</p></details><p>The accent has been added. Your answer is saved with this spelling.</p></section>`;
   footer='<button class="btn primary block" data-placement-next>Continue</button>';
  }
  else if(q){
   p().tokens ||= [];p().order ||= shuffle((q.format==='order'?q.tokens:q.options)?.map((_,i)=>i)||[]);
   const source=q.passageId?l.steps.find(s=>s.id===q.passageId):null;
   body=html`<section class="grammar-question"><span class="kicker">${p().level} · ${p().answers.length+1} of ${p().queue.length}</span><h1>${q.prompt}</h1>${source?raw(html`<article class="course-passage"><p lang="it" data-italian-sentence>${source.it}</p></article>`):''}${q.translation?raw(html`<p class="grammar-translation">${q.translation}</p>`):''}${q.context?raw(html`<p class="grammar-sentence" lang="it" data-italian-sentence>${q.context}</p>`):''}${q.format==='choice'?raw(html`<div class="grammar-choices">${raw(p().order.map(i=>html`<button class="choice ${p().selected===i?'selected':''}" data-placement-choice="${i}" aria-pressed="${p().selected===i}">${q.options[i]}</button>`).join(''))}</div>`):q.format==='order'?raw(html`<div class="grammar-built" aria-label="Your sentence">${p().tokens.length?raw(p().tokens.map((i,k)=>html`<button type="button" class="chip" data-placement-remove="${k}">${q.tokens[i]}</button>`).join('')):raw('<span class="muted">Tap the words to build the sentence</span>')}</div><div class="grammar-tokens">${raw(p().order.map(i=>html`<button type="button" class="chip" data-placement-token="${i}" ${p().tokens.includes(i)?raw('disabled'):''}>${q.tokens[i]}</button>`).join(''))}</div>`):raw(html`<label for="placement-answer">Your answer</label><input id="placement-answer" data-placement-input value="${p().draft}" autocomplete="off" autocapitalize="none" spellcheck="false">`)}<details><summary>Word meanings</summary>${raw(l.steps.filter(s=>s.kind==='words').flatMap(s=>s.words).map(w=>html`<p>${w.it} · ${w.en}</p>`).join(''))}</details><p class="course-practice-note">Answers are saved until the end of this set. Looking up a word makes this a supported response.</p></section>`;
   footer=html`<button class="btn primary block" data-answer ${q.format==='choice'?p().selected===null?raw('disabled'):raw(''):q.format==='order'?p().tokens.length!==q.tokens.length?raw('disabled'):raw(''):!p().draft.trim()?raw('disabled'):raw('')}>Continue</button><div class="journey-tools"><button class="btn ghost" data-unknown>I don’t know</button><button class="btn ghost" data-stop>Finish here</button></div>`;
  }
  root.innerHTML=html`<div class="grammar-shell"><header class="grammar-header"><a class="btn ghost" href="#/course">${raw(icon('chevron',{size:16}))} Your course</a><span class="kicker">Starting point</span></header><main class="grammar-scroll">${raw(body)}</main><footer class="grammar-footer">${raw(footer)}</footer></div>`;panel.decorate();save();
  root.querySelector('details')?.addEventListener('toggle',e=>{if(alive()&&e.target.open&&!p().pending){p().assisted=true;save();}});
 }
 function submit(unknown){const q=question();if(!alive()||!q||p().pending)return;const l=lesson(),target=l.targets.find(t=>t.id===q.target);store.recordLearningAttempt({id:session.id+':exposure:'+session.index,sessionId:session.id,index:session.index,entryId:'g:'+l.id,objectiveId:q.target,kind:'grammar',policy:'grammar-v2',contentVersion:2,variantId:q.id,exposureGroup:q.exposureGroup||q.id,contextId:q.contextKey,skill:q.facet,facet:q.facet,requiredFacets:target.facets,minIndependent:target.minIndependent,requiresProduction:target.requiresProduction,modality:target.modality,grammarPhase:'guided',mode:'recognition',outcome:'ungraded',ok:false,firstAttempt:false,assistance:['placement'],xp:0,countStats:false});const value=unknown?'':q.format==='choice'?q.options[p().selected]:q.format==='order'?p().tokens.map(i=>q.tokens[i]).join(' '):p().draft;const result=assessPlacement(q,value,p().assisted,{accentStrict:store.settings.accentStrict});const answer={...item(),...result,unknown};if(result.submission?.ok&&result.submission.matchKind==='accent-only'&&!unknown){p().pending=answer;p().draft=result.submission.displayText;save();draw();}else completeAnswer(answer);}
 function completeAnswer(answer){if(!alive())return;p().answers.push(answer);delete p().pending;p().draft='';p().selected=null;p().assisted=false;p().order=null;p().tokens=[];session.index++;if(p().answers.length>=p().queue.length)finish();else{save();draw();}}
 const click=async e=>{try{const b=e.target.closest('button');if(!b||!alive())return;if(b.hasAttribute('data-placement-next')&&p().pending)completeAnswer(p().pending);else if(b.hasAttribute('data-begin'))await begin('A1');else if(b.hasAttribute('data-more')){const level=p().suggestion.continueAt;await begin(level);}else if(b.hasAttribute('data-use')){const level=p().suggestion.level||p().suggestion.continueAt;p().finished=true;save();store.setLearningPreference('courseLevel',level);location.hash='#/course';}else if(b.hasAttribute('data-placement-choice')){p().selected=Number(b.dataset.placementChoice);save();draw();}else if(b.hasAttribute('data-placement-token')){const i=Number(b.dataset.placementToken);p().tokens ||= [];if(!p().tokens.includes(i))p().tokens.push(i);save();draw();}else if(b.hasAttribute('data-placement-remove')){p().tokens.splice(Number(b.dataset.placementRemove),1);save();draw();}else if(b.hasAttribute('data-answer'))submit(false);else if(b.hasAttribute('data-unknown'))submit(true);else if(b.hasAttribute('data-stop'))finish(true);}catch(error){if(alive())toast(error.message);}};
 const input=e=>{if(!alive())return;if(e.target.matches('[data-placement-input]')){p().draft=e.target.value;save();root.querySelector('[data-answer]').disabled=!p().draft.trim();}};
 const cleanup=()=>{if(disposed)return;const wasOwned=owned();save();disposed=true;panel.destroy();root.removeEventListener('click',click);root.removeEventListener('input',input);viewport.destroy();if(wasOwned)setChrome({tabs:true,back:true});};
 if(p().started&&!p().suggestion){try{await loadGrammarStage(p().level);}catch(error){if(!alive()){cleanup();return;}cleanup();root.innerHTML=html`<div class="empty"><p>${error.message}</p><button class="btn primary" data-placement-retry>Retry saved placement</button><a href="#/course">Your course</a></div>`;root.querySelector('[data-placement-retry]').addEventListener('click',()=>{if(owned())return render(root);});return;}}
 if(!alive()){cleanup();return;}
 root.addEventListener('click',click);root.addEventListener('input',input);if(p().started&&!p().suggestion&&!item())finish(true);else draw();
 return cleanup;
}
