import test from 'node:test';
import assert from 'node:assert/strict';
import {createConversationSpeechSession} from '../../js/conversations/speech-session.js';
import {createBrowserPCMCapture,encodePCM16Wav,resamplePCM} from '../../js/ai/pcm-capture.js';
const deferred=()=>{let resolve;const promise=new Promise(yes=>resolve=yes);return{promise,resolve};};
const tick=()=>new Promise(resolve=>setTimeout(resolve,0));
const audio=()=>({samples:new Float32Array(1600).fill(.2),sampleRate:16000,duration:.1,blob:encodePCM16Wav(new Float32Array(1600).fill(.2),16000)});
function fixture(options={}){
 const events=[],saved=[];let starts=0,sends=0,replies=0,voiceCalls=0,current=true,captureOptions;
 const controller={state:{draft:null,turns:[]},busy:false,error:null,async saveDraft(text,extras){events.push('draft');this.state.draft={typedText:text,...extras};return this.state.draft;},async send(){sends++;events.push('send');const turnId='learner-'+sends;this.state.turns.push({role:'learner',turnId,originalText:this.state.draft.typedText});this.state.draft=null;return options.sendResult||{committed:true,turnId,reply:{role:'partner',turnId:'partner-'+sends,displayText:'Ciao Ada.'},error:null};},async reply(){replies++;this.state.turns.push({role:'partner',turnId:'retry-'+replies,displayText:'Come stai?'});return true;},cancel(){events.push('cancel');}};
 const capture={supported:()=>true,async start(value){captureOptions=value;starts++;events.push('capture:start');},async stop(){events.push('capture:stop');},async finish(){events.push('capture:finish');return audio();}};
 const speech={readiness:()=>({recognition:true,voice:true,vad:true}),recognizer:{async transcribe(){events.push('recognize');return options.recognition?options.recognition():{recognizedText:'Mi chiamo Ada.',uncertain:false};}},voice:{async speak(text){voiceCalls++;events.push('voice:'+text);if(options.voice)await options.voice();},stop(){events.push('voice:stop');}},vad:{createSession(){return{process:()=>.9};}}};
 const session=createConversationSpeechSession({controller,repository:{async saveRecording(...args){saved.push(args);return{audioId:'explicit-save'};}},threadId:'thread',isCurrent:()=>current,speech:options.absent?null:speech,capture,replay:{play:async()=>events.push('replay'),stop(){}},bindLifecycle:false});
 return{session,controller,events,saved,speech,get starts(){return starts;},get sends(){return sends;},get replies(){return replies;},get voiceCalls(){return voiceCalls;},utterance:()=>captureOptions.onUtterance(audio()),stale(){current=false;}};
}
test('absent installed local speech fails closed without requesting a microphone',async()=>{const f=fixture({absent:true});assert.equal(f.session.snapshot.readiness.recorded,false);await assert.rejects(f.session.startManual(),/Install and verify/);assert.equal(f.starts,0);await f.session.dispose();});
test('manual PCM stop persists original recognition; edit/send retains provenance and explicit save only',async()=>{const f=fixture();await f.session.startManual();await f.session.stopRecording();assert.equal(f.session.snapshot.state,'review');assert.equal(f.sends,0);assert.equal(f.saved.length,0);assert.ok(f.events.indexOf('capture:stop')<f.events.indexOf('recognize'));await f.session.edit('Mi chiamo Eva.');assert.equal(f.controller.state.draft.recognizedText,'Mi chiamo Ada.');assert.equal(f.controller.state.draft.inputProvenance.transcriptEdits[0].before,'Mi chiamo Ada.');assert.equal(f.controller.state.draft.inputProvenance.recognitionUncertain,false);await f.session.send();assert.equal(f.sends,1);assert.equal(f.session.snapshot.state,'idle');assert.equal(f.saved.length,0);await f.session.replay();assert.ok(f.events.includes('replay'));await assert.rejects(f.session.saveRecording(),/explicit/);await f.session.saveRecording({consentAt:Date.now()});assert.equal(f.saved.length,1);assert.equal(f.saved[0][1],'learner-1');await f.session.dispose();assert.equal(f.session.snapshot.hasTemporaryAudio,false);});
test('a saved learner turn with failed partner generation retries only the partner',async()=>{const f=fixture({sendResult:{committed:true,turnId:'learner-1',reply:null,error:'Reply needs checking.'}});await f.session.startManual();await f.session.stopRecording();await f.session.send();assert.equal(f.session.snapshot.state,'reply-needed');assert.equal(f.session.snapshot.draft,null);assert.equal(f.session.snapshot.canSaveRecording,true);await assert.rejects(f.session.send(),/Review/);assert.equal(await f.session.retryReply(),true);assert.equal(f.sends,1);assert.equal(f.replies,1);assert.equal(f.voiceCalls,1);await f.session.dispose();});
test('uncommitted send keeps review draft and never speaks a reply',async()=>{const f=fixture({sendResult:{committed:false,turnId:null,reply:null,error:'Storage conflict.'}});await f.session.startManual();await f.session.stopRecording();await f.session.send();assert.equal(f.session.snapshot.state,'review');assert.ok(f.session.snapshot.draft);assert.equal(f.voiceCalls,0);assert.equal(f.session.snapshot.canSaveRecording,false);await f.session.dispose();});
test('late recognition after lifecycle pause never writes a draft or sends',async()=>{const wait=deferred(),f=fixture({recognition:()=>wait.promise});await f.session.startManual();const pending=f.session.stopRecording();await tick();await f.session.pause();wait.resolve({recognizedText:'Risposta tardiva.',uncertain:false});await assert.rejects(pending,{name:'AbortError'});assert.equal(f.controller.state.draft,null);assert.equal(f.sends,0);assert.equal(f.session.snapshot.hasTemporaryAudio,false);assert.equal(f.starts,1);await f.session.dispose();});
test('handsfree uncertainty requires explicit review, while verified recognition alternates playback and capture',async()=>{const uncertain=fixture({recognition:async()=>({recognizedText:'Due biglietti?',uncertain:true})});await uncertain.session.startHandsfree();uncertain.utterance();await tick();assert.equal(uncertain.session.snapshot.state,'review');assert.equal(uncertain.sends,0);assert.equal(uncertain.controller.state.draft.inputProvenance.recognitionUncertain,true);await uncertain.session.dispose();const voice=deferred(),f=fixture({voice:()=>voice.promise});await f.session.startHandsfree();f.utterance();await tick();assert.equal(f.session.snapshot.state,'speaking');assert.equal(f.starts,1);assert.equal(f.sends,1);voice.resolve();await tick();assert.equal(f.session.snapshot.state,'listening');assert.equal(f.starts,2);await f.session.pause();assert.equal(f.session.snapshot.state,'paused');await f.session.dispose();});
test('missing uncertainty declaration is uncertain and missing VAD gates handsfree',async()=>{const f=fixture({recognition:async()=>({recognizedText:'Ciao.'})});delete f.speech.vad;await assert.rejects(f.session.startHandsfree(),/voice detector/);await f.session.startManual();await f.session.stopRecording();assert.equal(f.session.snapshot.draft.recognitionUncertain,true);await f.session.dispose();});
test('double start and double send cannot acquire or send twice',async()=>{const f=fixture(),voice=deferred();f.speech.voice.speak=()=>voice.promise;const start=f.session.startManual();await assert.rejects(f.session.startManual(),/already pending/);await start;await f.session.stopRecording();const send=f.session.send();await tick();await assert.rejects(f.session.send(),/pending/);assert.equal(f.sends,1);voice.resolve();await send;await f.session.dispose();});
test('recovered speech draft keeps uncertainty and never restarts capture or invents retained audio',async()=>{const f=fixture();f.controller.state.draft={mode:'recorded',typedText:'Due biglietti.',recognizedText:'due bietti',transcriptEdits:[{before:'due bietti',after:'Due biglietti.'}],inputProvenance:{recognitionUncertain:true}};assert.equal(f.session.restoreDraft(),true);assert.equal(f.session.snapshot.draft.recognitionUncertain,true);assert.equal(f.starts,0);assert.equal(f.session.snapshot.hasTemporaryAudio,false);await assert.rejects(f.session.startManual(),/existing draft/);await f.session.dispose();});
test('PCM resampling preserves duration and WAV header bounds/clipping',async()=>{const pcm=new Float32Array([2,-2,.5,NaN]),blob=encodePCM16Wav(pcm,16000),view=new DataView(await blob.arrayBuffer());assert.equal(blob.type,'audio/wav');assert.equal(view.getUint32(24,true),16000);assert.equal(view.getInt16(44,true),32767);assert.equal(view.getInt16(46,true),-32768);assert.equal(view.getInt16(50,true),0);assert.equal(resamplePCM(new Float32Array(48000),48000).length,16000);});
test('late microphone permission after cancellation stops the acquired track before connecting',async()=>{const permission=deferred();let stopped=0,contexts=0;const environment={isSecureContext:true,location:{href:'https://local.test/',origin:'https://local.test'},navigator:{mediaDevices:{getUserMedia:()=>permission.promise}},AudioContext:class{constructor(){contexts++;}},AudioWorkletNode:class{}};const capture=createBrowserPCMCapture({environment,workletURL:'https://local.test/worklet.js'}),abort=new AbortController(),pending=capture.start({signal:abort.signal});await tick();abort.abort();await capture.stop();permission.resolve({getTracks:()=>[{stop(){stopped++;}}]});await assert.rejects(pending,{name:'AbortError'});assert.equal(stopped,1);assert.equal(contexts,0);});
