import UIKit
import Metal

struct GGUFCase:Codable {var id:String;var instructions:String;var prompt:String;var grammar:String;var review:String}
final class ProbeEngine:@unchecked Sendable {
    var handle:UnsafeMutableRawPointer?
    func load(_ path:String) -> String? {var error:UnsafeMutablePointer<CChar>?;handle=parola_model_create(path,99,&error);if let error{defer{free(error)};return String(cString:error)};return handle==nil ? "No native engine was created." : nil}
    func run(_ probe:GGUFCase) -> [String:Any] {var input:Int32=0,output:Int32=0,error:UnsafeMutablePointer<CChar>?;let started=Date(),raw=parola_generate(handle,probe.instructions,probe.prompt,probe.grammar,512,&input,&output,&error);var row:[String:Any]=["id":probe.id,"review":probe.review,"elapsedMs":Date().timeIntervalSince(started)*1000,"inputTokens":input,"outputTokens":output,"observedPhysicalFootprintBytes":parola_memory_footprint(),"ok":raw != nil];if let raw{row["raw"]=String(cString:raw);free(raw)};if let error{row["error"]=String(cString:error);free(error)};return row}
    deinit {parola_model_destroy(handle)}
}
@MainActor final class GGUFProbeController:UIViewController {
    let status=UILabel(),input=UITextView(),output=UITextView(),send=UIButton(type:.system),engine=ProbeEngine(),queue=DispatchQueue(label:"parola.native.inference",qos:.userInitiated)
    var report:[String:Any]=[:],template:GGUFCase?
    var documents:URL {FileManager.default.urls(for:.documentDirectory,in:.userDomainMask)[0]}
    override func viewDidLoad(){super.viewDidLoad();view.backgroundColor = .systemBackground;status.numberOfLines=0;status.text="Parola native Qwen investigation\nLoading the pinned local 8B model…";input.text="Non ho ancora prenotato la visita. Vorrei telefonare domani.";input.font = .preferredFont(forTextStyle:.body);input.backgroundColor = .secondarySystemBackground;output.isEditable=false;output.font = .preferredFont(forTextStyle:.body);send.setTitle("Invia al modello locale",for:.normal);send.isEnabled=false;send.addTarget(self,action:#selector(sendMessage),for:.touchUpInside);let stack=UIStackView(arrangedSubviews:[status,input,send,output]);stack.axis = .vertical;stack.spacing=12;stack.translatesAutoresizingMaskIntoConstraints=false;view.addSubview(stack);NSLayoutConstraint.activate([stack.leadingAnchor.constraint(equalTo:view.safeAreaLayoutGuide.leadingAnchor,constant:16),stack.trailingAnchor.constraint(equalTo:view.safeAreaLayoutGuide.trailingAnchor,constant:-16),stack.topAnchor.constraint(equalTo:view.safeAreaLayoutGuide.topAnchor,constant:16),stack.bottomAnchor.constraint(equalTo:view.safeAreaLayoutGuide.bottomAnchor,constant:-16),input.heightAnchor.constraint(equalToConstant:110)]);investigate()}
    func save(){report["recordedAt"]=ISO8601DateFormatter().string(from:Date());if let data=try? JSONSerialization.data(withJSONObject:report,options:[.prettyPrinted,.sortedKeys]){try? data.write(to:documents.appendingPathComponent("native-qwen.json"))}}
    func investigate(){guard let url=Bundle.main.url(forResource:"qwen-native-cases",withExtension:"json"),let cases=try? JSONDecoder().decode([GGUFCase].self,from:Data(contentsOf:url))else{status.text="The frozen trial input is missing.";return};template=cases.first(where:{$0.id=="h-negation-completion"});let model=documents.appendingPathComponent("Qwen3-8B-Q4_K_M.gguf").path;report=["kind":"native-Qwen-iPhone-simulator-trial","simulatedModel":"iPhone 16 Pro Max","simulatedOS":UIDevice.current.systemVersion,"hostExecution":"M1 Max32GB; simulator host resources, not physical iPhone performance or fit","runtime":"llama.cpp b11146, pinned7fe450e19305b828c199d602c23a8337aaa1f03b, own arm64 iOS simulator static build","model":"official Qwen3-8B-Q4_K_M, pinned7c41481f57cb95916b40956ab2f0b139b296d974","metalDevice":MTLCreateSystemDefaultDevice()?.name ?? "none","contextTokens":4096,"outputLimit":512,"inputRevision":"frozen-native-heldout-v1","sampling":["temperature":0.7,"topP":0.8,"topK":20,"presencePenalty":1.5,"seed":42,"thinking":false],"languageQualityReviewed":false,"productionApproved":false,"rows":[]];save()
        let engine=self.engine
        queue.async {let started=Date(),error=engine.load(model),loadMs=Date().timeIntervalSince(started)*1000;DispatchQueue.main.sync{self.report["loadMs"]=loadMs;self.report["modelBytes"]=parola_model_bytes(engine.handle);self.report["postLoadPhysicalFootprintBytes"]=parola_memory_footprint();if let error{self.report["loadError"]=error;self.status.text="The native local model could not load.";self.output.text=error;self.report["finished"]=true;self.save()}};if error != nil{return};var rows:[[String:Any]]=[];for probe in cases{rows.append(engine.run(probe));let captured=rows;DispatchQueue.main.sync{self.report["rows"]=captured;self.status.text="Parola native Qwen investigation\nMeasured \(captured.count)/\(cases.count) frozen situations.\nSimulator host, not a phone quality release.";self.save()}};let completed=rows;DispatchQueue.main.async{self.report["finished"]=true;self.status.text="Parola native Qwen investigation\nThe bounded local trial is complete.\nQuality review and physical iPhone tests are still required.";self.output.text=completed.last?["raw"] as? String ?? String(describing:completed.last?["error"]);self.send.isEnabled=true;self.save()}}
    }
    @objc func sendMessage(){guard send.isEnabled,var probe=template else{return};send.isEnabled=false;let text=input.text!;probe.prompt="{\"committedHistory\":[],\"currentRequest\":{\"text\":\(String(data:try! JSONEncoder().encode(text),encoding:.utf8)!),\"recognitionUncertain\":false,\"support\":\"free\"}}";let request=probe,engine=self.engine;queue.async{let row=engine.run(request);DispatchQueue.main.async{self.output.text=row["raw"] as? String ?? String(describing:row["error"]);self.report["manualResponse"]=row;self.send.isEnabled=true;self.save()}}}
}
@main final class GGUFPrototypeDelegate:UIResponder,UIApplicationDelegate {var window:UIWindow?;func application(_ application:UIApplication,didFinishLaunchingWithOptions options:[UIApplication.LaunchOptionsKey:Any]?) -> Bool {window=UIWindow(frame:UIScreen.main.bounds);window?.rootViewController=GGUFProbeController();window?.makeKeyAndVisible();return true}}
